### ISSUE TITLE
Continuous disconnects.

### ISSUE THREAD

**Issue by Squishy47** [iscsi-osx/iSCSIInitiator#102]
Hi, I've just gotten the latest prebuilt version working on High Sierra connecting to Netgear ReadyNas. 
i'm using the drive as a timemachine backup. 
if i leave it alone the drive stays connected. If I open an app, say VS Code, the drive will disconnect with MacOS saying the drive has not been disconnected properly.
iscsictl login...  : only 1 connection allowed...
iscsictl list luns... : no active luns.
iscsictl logout... : input/output error.
disk utility will not show anything, drives or devices.

Only thing that seems to fix it is rebooting.
system log is showing: 
`Aug 26 13:58:45 User com.apple.xpc.launchd[1] (com.github.iscsi-osx.iscsid[93]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]`

Please forgive my lack of knowledge of terminal, etc..., i'm learning, slowly...:)

**Comment by nsinenian** [comment]
This sounds like a repeatable issue.

Can you please use Wireshark (www.wireshark.org) to capture traffic between your machine and the NAS just through the disconnect process?

That is, run wireshark to log traffic, induce a disconnect event by running VS Code as you say, then stop the capture and post.

**Comment by Squishy47** [comment]
Hey. I may have been a bit apprehensive jumping on the issue. I have not been able to induce the issue by opening an app, the disconnecting has been semi-regular but I've not been able to tie it to a particular cause. I managed to capture one of the disconnects using wireshark. the file is too big to attach i've added a link to download it https://www.dropbox.com/s/vx72deoodjk8bx3/isici%20-%20netgear%20monitor.pcapng?dl=0

**Comment by Squishy47** [comment]
So i tried the over ethernet and it didn't seem to make a difference. I'll have to do some more testing but i upgraded to Mojave now, so i'll try again when Mojave is supported :).

**Comment by Squishy47** [comment]
I have just reinstalled the latest release and it is working flawlessly. installed added target, tried to login but was getting errors. rebooted and the drive are showing up and do not disconnect. putting the laptop to sleep or restarting and the drives show up again after a few mins. Not sure why i was getting errors before.
