### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by abonillasuse** [iscsi-osx/iSCSIInitiator#13]
With the updated code, the build is much gentler, but the install fails - How do you usually install?

Either sudo or as authorized admin I cannot install it on El Capitan.

 MacPro in ~/Documents/iSCSIInitiator
± |master ?:2 ✗| → sudo ./install.sh
cp: /usr/sbin/iscsid: Operation not permitted
cp: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: Operation not permitted
chmod: /usr/sbin/iscsid: No such file or directory
chown: /usr/sbin/iscsid: No such file or directory
chmod: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
chown: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
cp: /usr/bin/iscsictl: Operation not permitted
chmod: /usr/bin/iscsictl: No such file or directory
/Library/Extensions/iSCSIInitiator.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
/System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory

 MacPro in ~/Documents/iSCSIInitiator
± |master ?:2 ✗| → sh install.sh
cp: /usr/sbin/iscsid: Operation not permitted
cp: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: Operation not permitted
chmod: /usr/sbin/iscsid: No such file or directory
chown: /usr/sbin/iscsid: No such file or directory
chmod: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
chown: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
cp: /usr/bin/iscsictl: Operation not permitted
chmod: /usr/bin/iscsictl: No such file or directory
/Library/Extensions/iSCSIInitiator.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
/System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory

**Comment by nsinenian** [comment]
Have you tried disabling SIP prior to installation? (this is outlined in README.md) 

The new security features in OS X prevent modification of certain folders (even by root) unless they are modified by a signed installer. Once we're happy with the code and put together an installer this won't be an issue (I think, but we'll need to check). In the mean time I think disabling SIP, installing and then re-enabling SIP should work.

**Comment by lungj** [comment]
El Capitan has a new security feature that disables writing to places like `/usr/sbin` and `/System`; while the files in question could be installed elsewhere, SIP, as @nsinenian mentions above, needs to be disabled to load an unsigned kext anyway. Apple has an application process to approve signed Kexts that is different from the code signing process for regular applications so even if you have an Apple Developer Connection account, you're likely going to need to use this workaround.

**Comment by abonillasuse** [comment]
I'm familiar, I just thought that didn't happen as root. Thanks for the heads up.

**Comment by nsinenian** [comment]
Unless we come up with something better, I think that we'll operate in this
mode until we're comfortable that the source is bug-free and compatible
with a large number of NAS devices, after which I'll get everything (or as
much as possible) signed.

**Comment by abonillasuse** [comment]
worked for me, this can be closed...
