### ISSUE TITLE
specified target name is not a valid IQN or EUI-64 identifier

### ISSUE THREAD

**Issue by abonillasuse** [iscsi-osx/iSCSIInitiator#14]
Ive tried to add a target as documented but get an error instead

○ → iscsictl add target iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant,192.168.124.82:3260 -interface en0
iscsictl: The specified target name is not a valid IQN or EUI-64 identifier

I wonder if the additional .name.etc. are causing it to misinterpret the validity of the identifier.

A discovery from linux shows

w530:~ # iscsiadm -m discovery -t st -p 192.168.124.83
192.168.124.82:3260,1 iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant
192.168.124.83:3260,2 iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant

**Comment by nsinenian** [comment]
Looks like there was a bug (an omission) in the regex matching that didn't allow for dashes.  The last commit should address this, please try again.

Please let me know what kind of target (OS/NAS) and version you're using, and how compatible you find the initiator to be.  We'd like to update the compatibility list as we get feedback.  Thank you.

**Comment by abonillasuse** [comment]
Thanks, this has fixed it.
