### ISSUE TITLE
unable to mount target

### ISSUE THREAD

**Issue by abonillasuse** [iscsi-osx/iSCSIInitiator#16]
I was unable to get the LUNs to mount. I wonder if the documentation is correct (as the iscsictl is expecting the LUN or if the target is specified without a LUN ID)

The command hangs...

 MacPro in ~
○ → iscsictl mount iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant
^C

 MacPro in ~
○ → sudo iscsictl mount iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant
^C

**Comment by lungj** [comment]
Here is how I mount an iSCSI target in 10.11:
`sudo iscsictl add target mytarget,127.0.0.1:3260`
`sudo iscsictl login mytarget,127.0.0.1:3260`
`sudo iscsictl mount mytarget,127.0.0.1:3260`

where 127.0.0.1:3260 is an `ssh` local tunnel.

**Comment by nsinenian** [comment]
As an additional note, you shouldn't need to explicitly mount.  It's there for convenience, in case a user needs to unmount/remount all volumes for a given target.

After login, volumes should be mounted automatically.  If you're not seeing anything in finder, please ensure check the OS X disk utility application to see if the drive shows up at all.  If it does not show up, please look at the output of `ioreg` on the command-line and let us know what you see under `iscsi`.  For example, with no targets connected, you should see:

````
...
 +-o com_github_iscsi_osx_iSCSIInitiator  <class com_github_iscsi_osx_iSCSIInitiator, id 0x1000003b1, regi$
      | +-o com_github_iscsi_osx_iSCSIVirtualHBA  <class com_github_iscsi_osx_iSCSIVirtualHBA, id 0x1000003ba, $
      |   +-o com_github_iscsi_osx_iSCSIInitiatorClient  <class com_github_iscsi_osx_iSCSIInitiatorClient, id 0$
...
````
With some targets connected, you should see additional entries.  The output will help us with debugging if the targets do not show up.

**Comment by abonillasuse** [comment]
MacPro in ~
○ → sudo iscsictl login iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant,192.168.124.82:3260
The specified target cannot support additional connections

○ → ls /dev/disk
disk0    disk0s1  disk0s2  disk0s3  disk1 

      +-o com_github_iscsi_osx_iSCSIInitiator  <class com_github_iscsi_osx_iSCSIInitiator, id 0x10000609b, registered, matched, active, busy 0 (660 ms), retain 6>
        +-o com_github_iscsi_osx_iSCSIVirtualHBA  <class com_github_iscsi_osx_iSCSIVirtualHBA, id 0x10000609c, registered, matched, active, busy 0 (659 ms), retain 8>
          +-o com_github_iscsi_osx_iSCSIInitiatorClient  <class com_github_iscsi_osx_iSCSIInitiatorClient, id 0x10000609e, !registered, !matched, active, busy 0, retain 6>
          +-o IOSCSIParallelInterfaceDevice@0  <class IOSCSIParallelInterfaceDevice, id 0x100006a68, registered, matched, active, busy 0 (658 ms), retain 12>
            +-o IOSCSITargetDevice  <class IOSCSITargetDevice, id 0x100006a6a, registered, matched, active, busy 0 (658 ms), retain 13>
              +-o IOSCSIHierarchicalLogicalUnit@0000000000000000  <class IOSCSIHierarchicalLogicalUnit, id 0x100006a6d, registered, matched, active, busy 0 (658 ms), retain 10>
                +-o IOSCSIPeripheralDeviceType00  <class IOSCSIPeripheralDeviceType00, id 0x100006a71, !registered, !matched, active, busy 0 (0 ms), retain 9>
                  +-o IOBlockStorageServices  <class IOBlockStorageServices, id 0x100006a75, registered, matched, active, busy 0 (0 ms), retain 6>
                    +-o IOBlockStorageDriver  <class IOBlockStorageDriver, id 0x100006a76, registered, matched, active, busy 0 (0 ms), retain 6>

**Comment by nsinenian** [comment]
So the first message is expected ("...cannot support additional..."); it looks like your'e connected to the target and only 1 connection is supported (logging in a second time will display that).  The `ioreg` output tells me that the the OS X SCSI stack has detected the LUN and created a device for it.  Do you see a disk that you can format in disk utility?

**Comment by abonillasuse** [comment]
Nope, nothing shows up. Neither under /dev/disk*

System Information will also only show the Adapter

SCSI Parallel Domain 2:

  Product:	iSCSI Virtual Host Bus Adapter
  Revision:	1.0
  Initiator Identifier:	1644799557

SCSI Target Device @ 0:

  Manufacturer:	SUSE
  Model:	RBD
  Revision:	4.0
  SCSI Target Identifier:	0
  SCSI Device Features:	
  SCSI Initiator/Target Features:	
  Peripheral Device Type:	0

SCSI Logical Unit @ 0:

  Manufacturer:	SUSE
  Model:	RBD
  Revision:	4.0
  LUN Address:	00:00:00:00:00:00:00:00

**Comment by abonillasuse** [comment]
Any way I can debug this?

**Comment by nsinenian** [comment]
I'm going to attempt to reproduce this using a virtual machine.  Some information that would be helpful (if you have time to perform any of these steps that would helpful):

1.  If you can provide us with a TCP dump that would be helpful (you can attach a file to a comment).  You can use [Wireshark](www.wireshark.com) to monitor traffic between your machine and the target.  Alternatively, you can use [tcpdump](https://support.apple.com/en-us/HT202013).  

If you can attach a packet dump showing all iSCSI traffic from the time you login for about 60 seconds, that would be very helpful.

2.  Does the target or initiator drop the connection after > 60 seconds (or thereabouts) of being connected? There is a timeout built into the initiator that will quit (logout) if the target does not respond to a specific task for more than 60 seconds.

3.  Provide a copy of the dmesg output (perhaps 60 seconds after you login).  (i.e., `sudo dmesg`) should print iscsi diagnostic messages.

4.  Do you have header or data digests enabled?  If so, can you disable them and try again?

**Comment by abonillasuse** [comment]
I've attached a tcpdump, it wasn't running for all 60 seconds. This was while doing a mount. Please rename the attached .txt to .pcap

Sandbox: cp(5601) System Policy: allow(0) file-write-create /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: cp(5601) System Policy: allow(0) file-write-mode /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: cp(5601) System Policy: allow(0) file-write-mode /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: cp(5601) System Policy: allow(0) file-write-mode /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: cp(5601) System Policy: allow(0) file-write-mode /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: chmod(5603) System Policy: allow(0) file-write-mode /usr/sbin/iscsid
Sandbox: chown(5605) System Policy: allow(0) file-write-owner /usr/sbin/iscsid
Sandbox: chown(5609) System Policy: allow(0) file-write-owner /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist
Sandbox: cp(5611) System Policy: allow(0) file-write-create /usr/bin/iscsictl
Sandbox: cp(5611) System Policy: allow(0) file-write-mode /usr/bin/iscsictl
Sandbox: cp(5611) System Policy: allow(0) file-write-mode /usr/bin/iscsictl
Sandbox: cp(5611) System Policy: allow(0) file-write-mode /usr/bin/iscsictl
Sandbox: cp(5611) System Policy: allow(0) file-write-mode /usr/bin/iscsictl
iscsi: Initializing virtual HBA
Resetting IOCatalogue.
hfs: mounted Recovery HD on device disk0s3
hfs: unmount initiated on Recovery HD on device disk0s3
iscsi: Sent PDU type 0x43
iscsi: Sending data length: aa
iscsi: Sent PDU type 0x43
iscsi: Sending data length: 11b
iscsi: Transfer size: 0 (sid: 0, cid: 0)
iscsi: Queued task 0 (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task 0 (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 36 (sid: 0, cid: 0)
iscsi: Queued task 0 (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 4 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 12 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 5 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 42 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 5 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 222 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 17 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 17 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 1 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 5 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 13 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 43 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 223 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 2 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 38 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
considerRebuildOfPrelinkedKernel prebuild rebuild has expired
iscsi: Transfer size: 2 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 38 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 34 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 34 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 34 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Sending data length: 20
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Received sense data (sid: 0, cid: 0)
iscsi: Processed sense data (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 6 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 14 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 66 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 2 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 10 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 37 (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed data-in PDU (sid: 0, cid: 0)
iscsi: Transfer size: 10 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Received sense data (sid: 0, cid: 0)
iscsi: Processed sense data (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 18 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Received sense data (sid: 0, cid: 0)
iscsi: Processed sense data (sid: 0, cid: 0)
iscsi: Bytes per second: -559038737 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Transfer size: 26 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Sent PDU type 0x1
iscsi: Received PDU type 33 (sid: 0, cid: 0)
iscsi: Received sense data (sid: 0, cid: 0)
iscsi: Processed sense data (sid: 0, cid: 0)
iscsi: Bytes per second: 71521 (sid: 0, cid: 0)
iscsi: Processed SCSI response (sid: 0, cid: 0)
iscsi: Sent PDU type 0
iscsi: Sending data length: c
iscsi: Transfer size: 30 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Received PDU type 63 (sid: 0, cid: 0)
iscsi: Received PDU type 0 (sid: 0, cid: 0)
iscsi: Transfer size: 30 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
iscsi: Received PDU type 32 (sid: 0, cid: 0)
iscsi: Sent PDU type 0

[iscsictl-1.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/31507/iscsictl-1.txt)
memory footprint until the target exits.
hfs: mounted Wireshark on device disk2s2
hfs: unmount initiated on Wireshark on device disk2s2
iscsi: Transfer size: 30 (sid: 0, cid: 0)
iscsi: Queued task <ptr> (sid: 0, cid: 0)
IOSCSIPeripheralDeviceType00::setPowerState(0x8b13552129e35fa9, 3 -> 2) timed out after 100833 ms
SIOCPROTODETACH_IN6: utun0 error=6
IOSCSIPeripheralDeviceType00::setPowerState(0x8b13552129e35fa9, 2 -> 1) timed out after 100872 ms

**Comment by abonillasuse** [comment]
I'm also unable to logout and log back in to test this further.
 MacPro in ~
○ → iscsictl list luns
iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant  <id 0, SUSE (RBD)>
	LUN 0  <type 0x00, SUSE (RBD)>
 MacPro in ~
○ → iscsictl logout iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant,192.168.124.82
^C
 MacPro in ~
○ → iscsictl logout iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant,192.168.124.83
^C
 MacPro in ~
○ → iscsictl logout iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant

It just hangs.

**Comment by nsinenian** [comment]
So the TCP dump does not contain much iSCSI traffic (was it run on the appropriate interface?).  It also looks like it wasn't run long enough (I've attached a sample file shown what you would expect to see...)

Do you have information about the iSCSI target you're using? (I know it's backed by RBD and you're using SUSE, but is the target software IET, by any chance?) 
[sample.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/34549/sample.txt)

**Comment by nsinenian** [comment]
Please let me know if you still experience these issues with the new beta release (with installer).
