### ISSUE TITLE
segfault while removing targets

### ISSUE THREAD

**Issue by abonillasuse** [iscsi-osx/iSCSIInitiator#17]
The iqn parsing might still be off since the 'add target' is still adding targets with a more random naming, I was removing the entry that was added without certain values and there was a segfault, perhaps as it removed a mounted target because the syntax caught more than one entry and did not block that well... 

MacPro in ~
○ → sudo iscsictl remove target iqn.2003-01.org.linux-iscsi.igw:sn,192.168.124.82:3260
Password:
The specified portal has been removed

 MacPro in ~
○ → iscsictl list targets
iqn.2003-01.org.linux-iscsi.igw:sn <inactive, static>
	192.168.124.83 <inactive, port 3260, interface default>
iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant <active, static, sid 0, tpgt 1, tsid 0x1>
	192.168.124.82 <active, cid 0, port 3260, interface en0>

 MacPro in ~
○ → sudo iscsictl remove target iqn.2003-01.org.linux-iscsi.igw:sn,192.168.124.83:3260
The specified portal has been removed

 MacPro in ~
○ → iscsictl list targets
iqn.2003-01.org.linux-iscsi.igw:sn <inactive, static>
Segmentation fault: 11

previously, it had blocked me from removing a connected target
 MacPro in ~
○ → iscsictl remove target iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant,192.168.124.82:3260
The specified portal is connected and cannot be removed

but again, this protection might have failed if the parsing is off due to the IQN naming used...

**Comment by nsinenian** [comment]
I am able to reproduce this problem.  There's a bug in `iscsictl` that doesn't properly remove the target the only a single portal is left.  I'll fix this shortly.  For now, you can restore operation by removing the target as a whole:

`sudo iscsictl remove target iqn.2003-01.org.linux-iscsi.igw.x86:sn.redundant`

**Comment by nsinenian** [comment]
This bug has now been fixed in build df6de61
