### ISSUE TITLE
Won't build on El Capitan

### ISSUE THREAD

**Issue by UnaClocker** [iscsi-osx/iSCSIInitiator#18]
I downloaded the latest source, ran ./build.sh in the main directory, and got this error message 3 times:
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iSCSIDaemon". The "-list" option can be used to find the names of the schemes in the project.
It's not building at all.

**Comment by nsinenian** [comment]
Should be fixed now (this was fixed earlier and somehow overwritten)

**Comment by 4ft35t** [comment]
I have the same issue with last code.

**Comment by jaccoh** [comment]
I have this issue as well:

MBP-Hoeve:iSCSIInitiator jhoeve$ git pull
Already up-to-date.
MBP-Hoeve:iSCSIInitiator jhoeve$ ./build.sh 
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iscsid". The "-list" option can be used to find the names of the schemes in the project.
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iscsictl". The "-list" option can be used to find the names of the schemes in the project.
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iSCSIInitiator". The "-list" option can be used to find the names of the schemes in the project.
MBP-Hoeve:iSCSIInitiator jhoeve$ 

Fresh pull.

**Comment by lungj** [comment]
Can you try opening iSCSIInitiator.xcodeproj in Xcode first and then trying build? If you have a problem with the `iscsid` target, I have a patch with that.

**Comment by jaccoh** [comment]
Opening it in XCode made it download some extra stuff. Now it does compile, all but one:
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iscsid". The "-list" option can be used to find the names of the schemes in the project.

**Comment by lungj** [comment]
I've just pushed a new commit with an updated `build.sh`; a `git pull` followed by `build.sh` should do the trick!

**Comment by jaccoh** [comment]
Awesome it builds now!

Now I'll turn SIP off in El Capitan and test it. Tomorrow.

**Comment by gonzoleeman** [comment]
I had build problems as well, but once I opened Xcode, it told me I needed to download some missing peaces. Once I did, I quite Xcode and the build.sh script worked.

**Comment by nsinenian** [comment]
I've shared the build schemes in XCode and added the scheme file to the repository. Now you should be able to build by running the script build.sh without opening Xcode (or doing anything else assuming you have the command line tools installed).

**Comment by gonzoleeman** [comment]
Would it be possible to install the command line tools if not already installed, and then close this issue? Something like "if /usr/bin/xcrun is not present run 'xcode-select --install'"?

**Comment by lungj** [comment]
I've made a branch named `xcodeinstaller` that should install Xcode if it isn't already, but I haven't tested it (due to a lack of a fresh machine to try it on). I think commit 7bc3d45f42988adec4134652fa97c344ee68e004 fixed the build issue described initially.
