### ISSUE TITLE
Compile warnings in iSCSIVirtualHBA.cpp

### ISSUE THREAD

**Issue by gonzoleeman** [iscsi-osx/iSCSIInitiator#21]
When building on OS X 10.11.2 El Capitan I got 3 compiler warnings for iSCSIVirtualHBA.cpp:

1. The is a switch statement with "default:" missing and not all enums listed
2. There are two places that "%z" is used for a debug format string

I have fixes for both, if you'd like me to submit a pull request.

That is, if you wish to fix such things. I'm just learning Xcode, so I'm starting small.

**Comment by nsinenian** [comment]
Please feel free to contribute such changes. We will review and accept the pull request as appropriate.

**Comment by gonzoleeman** [comment]
Thank you.

**Comment by gonzoleeman** [comment]
It looks like both of the errors I saw have been fixed.
