### ISSUE TITLE
Lost connection to ReadyNAS Device

### ISSUE THREAD

**Issue by iiukadmin** [iscsi-osx/iSCSIInitiator#22]
I have been able to get iSCSIInitiator running and connecting successfully between El Capitan and a ReadyNAS 104 created LUN.

Transferring files is working, however the device keeps disconnecting, a new iscsictl login is required to reconnect. OS X alert reports device not properly disconnected.

I've checked /var/log/system.log and I see the following messages that seem to be connected to the disconnect. (I've also attached the full system log file if useful).

Thanks

Dec 30 11:31:43 Batman kernel[0]: iscsi: Sending data length: 10000
Dec 30 11:31:43 Batman kernel[0]: iscsi: Transfer size: 332314 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Queued task 0x21d3b520 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Received PDU type 0x31 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Dataoffset: 65536 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Desired data length: 196608 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Sending final data out (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Sent PDU type 0x5 (sid: 0, cid: 0)
Dec 30 11:31:43 Batman kernel[0]: iscsi: Sending data length: 30000
Dec 30 11:31:48 Batman kernel[0]: iscsi: Transfer size: 135706 (sid: 0, cid: 0)
Dec 30 11:31:48 Batman kernel[0]: iscsi: Queued task 0x1d9e0b60 (sid: 0, cid: 0)
Dec 30 11:31:49 Batman kernel[0]: gfx: surf 63dcbef: SetIDMode: id=449545833 mode=0x24
Dec 30 11:31:49 Batman kernel[0]: gfx: surf 63dcbef: clientClose: 
Dec 30 11:31:55 Batman kernel[0]: iscsi: Received PDU type 0x20 (sid: 0, cid: 0)
Dec 30 11:31:55 Batman kernel[0]: iscsi: Sent PDU type 0x40 (sid: 0, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Failed to send NOP response (sid: 0, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sending data length: 71
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sending data length: 11b
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sent PDU type 0x44 (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sending data length: 10
Dec 30 11:32:05 Batman kernel[0]: iscsi: Deactivated connection (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Sent PDU type 0x46 (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Releasing session (sid 1)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Removed event sources (sid: 1, cid: 0)
Dec 30 11:32:05 Batman kernel[0]: iscsi: Released connection (sid: 1, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Task timeout for task 0x21d3b880 (sid: 0, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Connection timeout (sid: 0, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Releasing session (sid 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Bytes per second: 1308626 (sid: 0, cid: 0)
Dec 30 11:32:43 --- last message repeated 1 time ---
Dec 30 11:32:43 Batman kernel[0]: iscsi: Deactivated connection (sid: 0, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Removed event sources (sid: 0, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: iscsi: Released connection (sid: 0, cid: 0)
Dec 30 11:32:43 Batman kernel[0]: disk1s2: device/channel is not attached.
Dec 30 11:32:43 Batman kernel[0]: disk1s2: I/O error.
Dec 30 11:32:43 Batman kernel[0]: jnl: disk1s2: do_jnl_io: strategy err 0x5
Dec 30 11:32:43 Batman kernel[0]: jnl: disk1s2: end_transaction: only wrote 0 of 135680 bytes to the journal!
Dec 30 11:32:43 Batman kernel[0]: hfs: unmount initiated on iSCSI on device disk1s2
Dec 30 11:32:43 Batman kernel[0]: jnl: disk1s2: close: journal is invalid.  aborting outstanding transactions
Dec 30 11:32:43 Batman deleted[322]: normalizeUserMountpoint:736 volRoot failed for /Volumes/iSCSI
Dec 30 11:32:43 Batman deleted[322]: _validateVolume:758 unable to normalize volume: "/Volumes/iSCSI", vol: (null)
Dec 30 11:32:43 Batman kernel[0]: gfx: gfx: powerStateDidChangeTo: The display is awake.
Dec 30 11:32:43 Batman fseventsd[51]: disk logger: failed to open output file /Volumes/iSCSI/.fseventsd/0000000001166467 (No such file or directory). mount point /Volumes/iSCSI/.fseventsd
Dec 30 11:32:53 --- last message repeated 1 time ---
Dec 30 11:32:53 Batman kernel[0]: gfx: gfx: powerStateDidChangeTo: The display is asleep.
Dec 30 11:33:04 --- last message repeated 1 time ---
Dec 30 11:33:04 Batman kernel[0]: gfx: surf 63dcfef: SetIDMode: id=449763306 mode=0x24
Dec 30 11:33:04 Batman kernel[0]: gfx: surf 63dcfef: clientClose: 
Dec 30 11:33:04 Batman iscsid[439]: discovery is taking longer than the specified discovery interval. Consider increasing discovery interval
Dec 30 11:34:05 Batman kernel[0]: iscsi: Sent PDU type 0x43 (sid: 0, cid: 0)
Dec 30 11:34:05 Batman kernel[0]: iscsi: Sending data length: 71
Dec 30 11:34:05 Batman kernel[0]: iscsi: Sent PDU type 0x43 (sid: 0, cid: 0)

[system.log.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/74839/system.log.txt)

**Comment by nsinenian** [comment]
Does it drop the connection if you don't transfer files? (e.g., connect and just leave it alone).

If you are familiar with OS X property lists, can you please try adjusting (reducing) the value of the of the following keys of the kernel extension:

IOMaximumSegmentCountRead
IOMaximumSegmentCountWrite
IOMaximumSegmentByteCountRead
IOMaximumSegmentByteCountWrite

These keys may be found in the Info.plist file under the Kernel folder in the source.  You would have to set the values and reinstall the initiator (run uninstall.sh, edit Info.plist, build from sources then run install.sh).  Currently, the values for the first two are set to 512 and the last two are 8192.  From the debug outputs, it looks like the there is a task timeout (i.e., the target won't respond to a query from the initiator).  This can happen if you have connectivity problems (which I assume is not the case for you) or if the target doesn't support the I/O transfer size requested by the initiator (some targets do nothing instead of throwing an error). 

If you reduce this value, does it stop dropping the connections?  I have seen this occur on IET targets for sufficiently large values of the above keys.

**Comment by iiukadmin** [comment]
Feeling sheepish! - I think it was connectivity issue....
I've plugged the ReadyNAS directly into the MacMini, and no issues transferring files so far. It was plugged in via a switch, I'll try back on the switch tomorrow, with different cables, and see what happens.
 
Thanks for the help and Happy New Year.

**Comment by iiukadmin** [comment]
Update - Has been running fine for last four days. Can close the issue and confirm compatibility with Netgear ReadyNAS 104 (and most likely with any Netgear ReadyNAS OS 6.2 system).
