### ISSUE TITLE
Build Warnings using Xcode 7

### ISSUE THREAD

**Issue by gonzoleeman** [iscsi-osx/iSCSIInitiator#24]
I upgraded to Xcode 7, and I get a bunch of warnings now when building the initiator kernel module, all along the lines of:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/scsi/spi/IOSCSIParallelInterfaceController.h:1532:18: 'getWorkLoop' overrides a member function but is not marked 'override'

It looks like the build flag "-Wno-inconsistent-missing-override" needs to be added to the compilation of most of the other kernel files for the iSCSIInitiator" target to fix this, i.e. to:
* iSCSIPDUKernel.cpp
* iSCSIVirtualHBA.cpp
* iSCSITaskQueue.cpp
* iSCSIIOEventSource.cpp, and
* iSCSIInitiatorClient.cpp

(It is already set for iSCSIInitiator.cpp.)

**Comment by nsinenian** [comment]
Thanks, this should now be fixed.
