### ISSUE TITLE
Unable to locate iSCSIInitiator binaries; did you run build.sh without errors?

### ISSUE THREAD

**Issue by magic9669** [iscsi-osx/iSCSIInitiator#25]
I am not an expert by any means with BASH so please bear with me.  I ran the csrutil enable command first and foremost and after a reboot, i ran the sudo sh build.sh command.  I had to agree to terms and what not, but when I run the sudo sh install.sh command, I get the error above.  Not sure how to proceed.

Any help would be appreciated.

**Comment by nsinenian** [comment]
Please try again, should be fixed now.

**Comment by nsinenian** [comment]
Please use the installer (.dmg) for the 1.0.0-beta release.
