### ISSUE TITLE
Unable to run ./install.sh without error

### ISSUE THREAD

**Issue by jamrog** [iscsi-osx/iSCSIInitiator#26]
Hi there,

Thanks for making this, really appreciate it and would love to get up and running, unfortunately, I'm getting the following:

Jamess-iMac:Scripts jamrog$ ./install.sh 
cp: /Users/jamrog/Library/Developer/Xcode/DerivedData/iSCSIInitiator-aigtxpilzqrfppejydqcfhbzmveq/Build/Products/Debug/iscsid: No such file or directory
cp: /Users/jamrog/Library/Developer/Xcode/DerivedData/iSCSIInitiator-aigtxpilzqrfppejydqcfhbzmveq/Build/Products/Debug/com.github.iscsi-osx.iscsid.plist: No such file or directory
chmod: /Library/PrivilegedHelperTools/iscsid: No such file or directory
chown: /Library/PrivilegedHelperTools/iscsid: No such file or directory
chmod: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
chown: /System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
cp: /Users/jamrog/Library/Developer/Xcode/DerivedData/iSCSIInitiator-aigtxpilzqrfppejydqcfhbzmveq/Build/Products/Debug/iscsid.8: No such file or directory
/Library/Extensions/iSCSIInitiator.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
/System/Library/LaunchDaemons/com.github.iscsi-osx.iscsid.plist: No such file or directory
Jamess-iMac:Scripts jamrog$ 

Can anyone assist? I have run ./build.sh already.

Thanks,
James.

**Comment by jamrog** [comment]
This is after running the csrutil enable in Recovery Terminal and rebooting.

bash-3.2# csrutil status
System Integrity Protection status: enabled.
bash-3.2#

**Comment by nsinenian** [comment]
Please use the installer (.dmg) for the 1.0.0-beta release.
