### ISSUE TITLE
The specified target name is not a valid IQN or EUI-64 identifier

### ISSUE THREAD

**Issue by jamrog** [iscsi-osx/iSCSIInitiator#27]
Hi again,

Thanks for the installer. No errors installing.

Getting a new error:

Jamess-iMac:~ jamrog$ sudo iscsictl add target iqn.2015-1.workgroup:RAID.iscsi0.vg0.data1
iscsictl: The specified target name is not a valid IQN or EUI-64 identifier

Any ideas? This same target shows in globalSAN which sees it and connects.

**Comment by nsinenian** [comment]
Can you try: "iqn.2015-**0**1.workgroup:RAID.iscsi0.vg0.data1".  I believe the IQN must include double digits on the month, per RFC3720 (page 32). Perhaps globalSAN is not as strict?  You'll also need to specify a portal, or you'll get another message after you put in a valid IQN.

**Comment by jamrog** [comment]
Thanks, that resolved it. By changing the IQN I managed to kill all my data in the process. My fault. Made a single IQN now, but it's saying that it doesn't exist. Just rebooting, then will continue trying.

Thanks ;)

**Comment by jamrog** [comment]
![screenshot 2016-01-19 21 51 45](https://cloud.githubusercontent.com/assets/16782691/12430183/e4b26f7a-bef6-11e5-836b-b5306315b0b4.png)
OK. So it's doing what it's supposed to do etc and it's seriously awesome, unfortunately this is happening.

**Comment by jamrog** [comment]
FYI, it's 5.93TB

**Comment by nsinenian** [comment]
Haven't seen this before. Does it work on smaller volumes, by any chance?

**Comment by jamrog** [comment]
I've wiped the NAS and I'm going to try see if sickrage/sab and plex work off AFP shares. 
Failing that I will get externalEnclosures. 






On Tue, Jan 19, 2016 at 5:38 PM -0800, "Nareg Sinenian" <notifications@github.com> wrote:












Haven't seen this before. Does it work on smaller volumes, by any chance?
