### ISSUE TITLE
top domain name does not always consist of 3 letters.

### ISSUE THREAD

**Issue by since19861019** [iscsi-osx/iSCSIInitiator#29]
iSCSIUtilsValidateIQN() checks if the specified target name conforms to RFC3721. However, the code assumes top domain name has always 3 letters (com,org,..). It is not case of country domains. So, it should be "[[:alnum:]]{2,3}" instead of "[[:alnum:]]{3}".
I also suggest that using double backslash to suppress 'unknown escape warnings' , e.g. "\\}" instead of  "\}" ( there are 4 regular expression string literals in the file) .

**Comment by BjoKaSH** [comment]
Actually, there should be no length constraint on the top level domain name label.  With new generic TLDs like .name or .museum (both active) and unknown other coming, it is impossible to set a good limit.

**Comment by nsinenian** [comment]
Fixed in 75fb91a (develop branch). Please verify and I'll close out.

**Comment by BjoKaSH** [comment]
Looks good to me.
Although I would have used ```{2,63}``` as in my now obsolete pull-request I was just creating (BjoKaSH/iSCSIInitiator@a5be467 ).
