### ISSUE TITLE
Under El Capitan 10.11.4 finder r/w error 

### ISSUE THREAD

**Issue by yabba235** [iscsi-osx/iSCSIInitiator#35]
Mounting iscsi target ok, but impossible write large files - The Finder can’t complete the operation because some data in “filename” can’t be read or written.(Error code -36) appears windows :(
Disk iscsi is formatting hfs+.
OS X 10.11.4 Beta (15e39d)

Free ( comadline mods :))  iscsi initiator from atto works very well on this same disk so it is a bug iscsiinitiator.

**Comment by nsinenian** [comment]
Please provide details so that we can reproduce and diagnose the issue.

What kind of target are you using?  (e.g., brand, model, etc.)
How large a file are you trying to copy?
Does the problem occur with a non-beta version of OS X?

**Comment by yabba235** [comment]
Hi !
My computer is mac mini later 2014  - 128GB ssd
My NAS is Qnap TS-453mini, 3xWD Red 3TB in raid5, lun size 250GB, sector 4kb size, no chap
About files size:
all more than 256MB impossible to copy or move
Unfortunately I don't use non beta os x ( but my old installed iscsi initiator from atto ( command line version from drobo dashboard ) works very well )
BTW:
Your project is fantastic, thank you:), maybe in the future you add some gui for this ?
Reg.
Tom
Dnia 13 lutego 2016 3:44 Nareg Sinenian &lt;notifications@github.com&gt; napisał(a):
Please provide details so that we can reproduce and diagnose the issue.What kind of target are you using? (e.g., brand, model, etc.)
How large a file are you trying to copy?
Does the problem occur with a non-beta version of OS X?—

**Comment by nsinenian** [comment]
Thanks for the details. Can you please try changing the following values in the kernel extension's Info.plist (property list) to see if it makes a difference in terms of writing a file larger than 256MB:

IOMaximumSegmentCountRead (currently set to 512)
IOMaximumSegmentByteCountRead (currently set to 8192)
IOMaximumSegmentCountWrite (currently set to 512)
IOMaximumSegmentByteCountWrite (currently set to 8192)

First unload the kext (or uninstall it) and edit the Info.plist file contained within the kext (then re-install the kext). I would suggest gradually reducing this value until it works, assuming that it is the problem. This is more of a test; if you can verify that it works with a smaller value we'll come up with a more permanent solution.

**Comment by yabba235** [comment]
With values reduce from 8192 to 4096 and from 512 to 256 no success.
Any pattern on it ?
Maybe one of this value must be increase - I really don't know about it :(
Dnia 13 lutego 2016 19:15 Nareg Sinenian &lt;notifications@github.com&gt; napisał(a):
Thanks for the details. Can you please try changing the following values in the kernel extension's Info.plist (property list) to see if it makes a difference in terms of writing a file larger than 256MB:IOMaximumSegmentCountRead (currently set to 512)
IOMaximumSegmentByteCountRead (currently set to 8192)
IOMaximumSegmentCountWrite (currently set to 512)
IOMaximumSegmentByteCountWrite (currently set to 8192)First unload the kext (or uninstall it) and edit the Info.plist file contained within the kext (then re-install the kext). I would suggest gradually reducing this value until it works, assuming that it is the problem. This is more of a test; if you can verify that it works with a smaller value we'll come up with a more permanent solution.—

**Comment by OvalII** [comment]
same here with QNAP HS-251,  2xWD Red 3TB in raid1, lun size 500GB FAT-32, sector 4kb size, no chap

**Comment by MMartinezV** [comment]
It works for me on El Capitan 10.11.3 (non beta). I'm able to transfer 1GB files using finder without problems.

I'm using a Netgear ReadyNAS Pro 4  (RNDP4420) upgraded to ReadyNAS OS 6. I'm using the latest iscsi-osx (modified to correct the memory leak during transfers).

Regards,

  Manu

**Comment by yabba235** [comment]
Is this modification include in the current binary ?

**Comment by MMartinezV** [comment]
Not yet in the release dmg, you have to install it from source.

**Comment by nsinenian** [comment]
Let's stick to the topic guys. I have experienced this issue in the past with IET targets. Basically, the OS X SCSI stack decides how much it is going to ask the iSCSI driver (this project) to transfer at a given time. If the chunk is too large, the target may reject the request or hang. I don't know of a way of figuring out how much a given target will support. I think it depends on the target's SCSI stack implementation. 

Anyway, OS X provides a mechanism for controlling the size of the request sent by the SCSI stack, which is contained in the kernel extension's Info.plist (e.g., IOMaximumSegmentCountRead; see my earlier post). Gradually reducing this number seemed to do the trick for IET. So the questions we need to answer are:

(1) what iSCSI target does Qnap use, I assume it runs linux, but which iSCSI implementation?
(2) is this the same issue as I described, and can we fix it by sufficiently lowering these values?
(3) if this is not the same issue, we'll need a traffic dump to determine what is happening.

Since I don't own one of these units, it is difficult for me to help with the diagnosis directly.

**Comment by nsinenian** [comment]
Also, please note that when playing around with these values, it may be good to reboot before testing to ensure that OS  X hasn't cached the kext.

**Comment by yabba235** [comment]
Answer for 1Q:
Qnap OS QTS 4.2.1 ( debian based ):
[/sbin] # ./iscsid  -v
iscsid version 2.0-871
[/sbin] # cd /sys/kernel/config/target] # cat version    Target Engine Core ConfigFS Infrastructure v4.1.0-rc2-ml on Linux/x86_64 on 3.12.6
/sys/kernel/config/target/iscsi] # cat lio_version
QNAP Linux-iSCSI Target v4.1.0-rc2
If you interresing: my working iscsi driver for atto works with IOSCSIArchitectureModelFamily.kext so I assume it uses a different method of implementation than your driver.
 
Dnia 15 lutego 2016 18:12 Nareg Sinenian &lt;notifications@github.com&gt; napisał(a):
Let's stick to the topic guys. I have experienced this issue in the past with IET targets. Basically, the OS X SCSI stack decides how much it is going to ask the iSCSI driver (this project) to transfer at a given time. If the chunk is too large, the target may reject the request or hang. I don't know of a way of figuring out how much a given target will support. I think it depends on the target's SCSI stack implementation.Anyway, OS X provides a mechanism for controlling the size of the request sent by the SCSI stack, which is contained in the kernel extension's Info.plist (e.g., IOMaximumSegmentCountRead; see my earlier post). Gradually reducing this number seemed to do the trick for IET. So the questions we need to answer are:(1) what iSCSI target does Qnap use, I assume it runs linux, but which iSCSI implementation?
(2) is this the same issue as I described, and can we fix it by sufficiently lowering these values?
(3) if this is not the same issue, we'll need a traffic dump to determine what is happening.Since I don't own one of these units, it is difficult for me to help with the diagnosis directly.—

**Comment by OvalII** [comment]
iscsi_trgt.conf for my QNAP

`[iSCSIPortal]
bServiceEnable=TRUE
servicePort=3260
initiatorBitmap00=00000001
bSupportMultiACL=1
log=TRUE
logFlags=1
targetIQNPrefix=iqn.2004-04.com.qnap:hs-251:iscsi.
targetBitmap00=00000001
LUNBitmap00=00000001

[init0Info]
initiatorIndex=0
initiatorIQN=iqn.2004-04.com.qnap:all:iscsi.default.ffffff
initiatorAlias=Default Policy
initiatorTargetBitmap00=00000001
initiatorLUNBitmap00=00000001

[InitiatorKey]
iqn.2004-04.com.qnap:all:iscsi.default.ffffff=0

[target0Info]
targetIndex=0
targetName=w
targetIQN=iqn.2004-04.com.qnap:hs-251:iscsi.w.e84762
targetAlias=W
bTargetDataDigest=FALSE
bTargetHeaderDigest=FALSE
targetStatus=0
targetInitBitmap00=00000001
targetLUNNumBitmap00=00000001
targetLUNBitmap00=00000001
bTargetClusterEnable=TRUE

[TargetKey]
target_iqn.2004-04.com.qnap:hs-251:iscsi.w.e84762=0

[target0Init0Info]
targetIndex=0
initiatorIndex=0
bCHAPEnable=FALSE
bMutualCHAPEnable=FALSE
CHAPUserName=undefined
CHAPPasswd=undefined
mutualCHAPUserName=undefined
mutualCHAPPasswd=undefined

[LUN0Info]
LUNIndex=0
LUNName=W_0
LUNPath=/share/CACHEDEV1_DATA
LUNMetaPath=/share/CACHEDEV1_DATA/.@iscsi.img/iSCSI-W_0-55f840cc:001
LUNSectorSize=512
LUNCapacity=512000
LUNFileCount=1
LUNThinAllocate=FALSE
LUNThreshold=-1
LUNStatus=2
LUNBackupStatus=0
LUNBackupPid=-1
LUNBackupJob=-1
LUNInitBitmap00=00000001
NAANaming=qnap
bRemoving=FALSE
LUNTargetBitmap00=00000001
WCEnable=0
FUAEnable=0
FBNumber=0
LUNSerialNum=b705152a-08b1-4824-beb1-5f21943c5eb0
LUNNAA=6e843b6b705152ad08b1d4824dbeb1d5
LUNAllocated=536871804928

[LUNKey]
LUN_W_0=0

[LUN0Init0Info]
LUNIndex=0
initiatorIndex=0
initiatorLUNNumber=-1
accessMode=1

[LUN0Target0Info]
LUNIndex=0
targetIndex=0
LUNNumber=0
LUNEnable=TRUE
`

**Comment by nsinenian** [comment]
I've tried to reproduce this problem using a virtual machine with an LIO target - and so far no success (I am unable to reproduce the problem). In order to help with the diagnosis, can one of you please record iSCSI traffic (using wireshark, for example) and post the file?

We would need to see what happens in terms of traffic the moment the R/W error occurs in finder.

**Comment by yabba235** [comment]
OK, in attach pcap file result of fail write six jpeg file ( 6.6MB size all ).
[dump2.pcap.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/171092/dump2.pcap.zip)

**Comment by nsinenian** [comment]
Please wipe iSCSI entirely and git pull, build and install from the `develop-bugfix-checkcondition` branch. Let me know if it makes a difference. If it does not, please send me the traffic.

The error is occurring during write and it's a low-level (SCSI-level) error, as opposed to an iSCSI error. That means the write CDB (as created by OS X and passed down to iSCSI) has some element that your target's SCSI stack doesn't like (it returns a SCSI check condition).

**Comment by yabba235** [comment]
Sorry, but i don&amp;#39;t developer i i can&amp;#39;t know how compiling apps :( I&amp;#39;m a simple user so you must build proper working app.  
 

  
    Dnia 13 marca 2016 18:16 Nareg Sinenian &amp;lt;notifications@github.com&amp;gt; napisał(a):
  
  
    Please wipe iSCSI entirely and git pull, build and install from the develop-bugfix-checkcondition branch. Let me know if it makes a difference. If it does not, please send me the traffic.

The error is occurring during write and it&amp;#39;s a low-level (SCSI-level) error, as opposed to an iSCSI error. That means the write CDB (as created by OS X and passed down to iSCSI) has some element that your target&amp;#39;s SCSI stack doesn&amp;#39;t like (it returns a SCSI check condition).

**Comment by nsinenian** [comment]
Well, the whole point of github is for developers to collaborate on development - it's not the iTunes App Store :)  I've attached a DMG for you to try:

[iSCSIInitiator-1.0.0-beta2-low-transaction-size.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/171149/iSCSIInitiator-1.0.0-beta2-low-transaction-size.zip)

Change the file extension to .DMG and then open the image. Data transfers may be slow, but this is just a test to determine if the problem is what I think it is... let me know if you can transfer large files.

**Comment by yabba235** [comment]
Sorry for  not to be develop, but i can testing beta version :)

Your link to beta2 not work :(

**Comment by nsinenian** [comment]
[iSCSIInitiator-1.0.0-beta2-low-transaction-size.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/171941/iSCSIInitiator-1.0.0-beta2-low-transaction-size.zip)

**Comment by yabba235** [comment]
Thank you - your beta 2 work good - I tested files from 256MB to 4GB- all r/w good :)
Only transfer is max. 52 MB/s ( half normal speed ( atto cmd line version iscsi initiator ))

**Comment by nsinenian** [comment]
This may take a few tries to optimize. I'm basically doing what I had suggested you guys try earlier - adjusting the IOMaximumSegmentCountWrite and similar values in the kernel extension's Info.plist. This does not require compiling any code, just unloading the kext, some text editing and reloading the kext.

Small values will guarantee compatibility but may be slower. Larger values are faster up to a point.

Here's another version for you to try:

[iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/174304/iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip)

**Comment by yabba235** [comment]
New version has this same speed - half of normal in my network.
So I must have luck to find optimal values - this is long work :)

**Comment by nsinenian** [comment]
How fast was the original version that did not work for files > 256MB?

**Comment by yabba235** [comment]
about 100MB/s 
 

  
    Dnia 15 marca 2016 17:59 Nareg Sinenian &amp;lt;notifications@github.com&amp;gt; napisał(a):
  
  
    How fast was the original version that did not work for files &amp;gt; 256MB? 
 
 
&amp;gt; On Mar 16, 2016, at 12:57 AM, yabba235 &amp;lt;notifications@github.com&amp;gt; wrote: 
&amp;gt;  
&amp;gt; New version has this same speed - half of normal in my network. 
&amp;gt; So I must have luck to find optimal values - this is long work :) 
&amp;gt;  
&amp;gt; — 
&amp;gt; You are receiving this because you commented. 
&amp;gt; Reply to this email directly or view it on GitHub: 
&amp;gt; https://github.com/iscsi-osx/iSCSIInitiator/issues/35#issuecomment-196921791 &amp;lt;https://github.com/iscsi-osx/iSCSIInitiator/issues/35#issuecomment-196921791&amp;gt;

**Comment by nsinenian** [comment]
I have prepared five variants for you try. Please let me know which ones work, and which is the fastest (even if not the fastest, please let me know which ones work for you).  Thanks.

[iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/176177/iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip)
[iSCSIInitiator-1.0.0-beta2-256-4096.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/176178/iSCSIInitiator-1.0.0-beta2-256-4096.dmg.zip)
[iSCSIInitiator-1.0.0-beta2-256-8192.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/176179/iSCSIInitiator-1.0.0-beta2-256-8192.dmg.zip)
[iSCSIInitiator-1.0.0-beta2-512-2048.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/176180/iSCSIInitiator-1.0.0-beta2-512-2048.dmg.zip)
[iSCSIInitiator-1.0.0-beta2-512-4096.dmg.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/176181/iSCSIInitiator-1.0.0-beta2-512-4096.dmg.zip)

**Comment by OvalII** [comment]
iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip seems work just pretty fine with my QNAP HS-251.
Waiting for PayPal donation address :)

**Comment by OvalII** [comment]
but not for iSCSIInitiator-1.0.0-beta2-512-4096.dmg.zip

**Comment by OvalII** [comment]
well just another little problem about 30 min away it have been unmount by itself

**Comment by yabba235** [comment]
This version ; iSCSIInitiator-1.0.0-beta2-256-8192.dmg.zip is unavaliable. And best work version is beta2-512-2048 - write speed 79MB/s,  read speed 90 MB/s.  Dnia 16 marca 2016 15:42 Nareg Sinenian &amp;lt;notifications@github.com&amp;gt; napisał(a):
   I have prepared five variants for you try. Please let me know which ones work, and which is the fastest (even if not the fastest, please let me know which ones work for you).  Thanks. iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip 
iSCSIInitiator-1.0.0-beta2-256-4096.dmg.zip 
iSCSIInitiator-1.0.0-beta2-256-8192.dmg.zip 
iSCSIInitiator-1.0.0-beta2-512-2048.dmg.zip 
iSCSIInitiator-1.0.0-beta2-512-4096.dmg.zip — You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub

**Comment by yabba235** [comment]
What is you speed r/w under HS-251 ? 
 

  
    Dnia 16 marca 2016 17:05 OvalII &amp;lt;notifications@github.com&amp;gt; napisał(a):
  
  
    iSCSIInitiator-1.0.0-beta2-256-2048.dmg.zip seems work just pretty fine with my QNAP HS-251. 
Waiting for PayPal donation address :)
