### ISSUE TITLE
how to use / documentation

### ISSUE THREAD

**Issue by heapxor** [iscsi-osx/iSCSIInitiator#38]
Hi,
Im desperately looking how to use this tool, is there any documentation? What should i do after installation... Thanks

**Comment by lungj** [comment]
Hi,

If you go to the wiki page (https://github.com/iscsi-osx/iSCSIInitiator/wiki), there's documentation on getting started, amongst other things, that you can browse using the table of contents on in the right hand side of the screen. There are also man pages for `iscsictl` once you've completed the installation (but the wiki is a good place to start).
