### ISSUE TITLE
missing binaries

### ISSUE THREAD

**Issue by heapxor** [iscsi-osx/iSCSIInitiator#39]
well, I installed package from img and the binaries are missing... no such file as iscsictl etc...

**Comment by heapxor** [comment]
or needles to say, it was installed into /private/tmp/iscsictl , bit weird target location.

**Comment by lungj** [comment]
I just tried the DMG from e70e54588e100aaffc52f86621e46e0e4d3b21ec . It appears to install to `/usr/local/bin/iscsictl`. I do have a  `/private/tmp/iscsictl`, but I think that was from one of my own manual builds. Can you check to see whether you have one in `/usr/local/bin` as well?
