### ISSUE TITLE
crash DiagnosticReports on reboots

### ISSUE THREAD

**Issue by MMartinezV** [iscsi-osx/iSCSIInitiator#41]
Hi,

I've been testing iscsi-osx for the last three weeks and for now it works very well.

Sometimes I've seen some iscsid-xxxx-crash reports at /Library/Logs/DiagnosticReports/ but, as everything was working fine I didn't pay any attention to them.

Today, I've realised that in fact, there are two, and only two iscsid-xxxx-crash reports each time after I do a reboot. That happens in my 3 El Capitan test machines. It does not depend on automounting any LUN, because I get a crash report in machines with or without auto-login enabled targets.

The text in the report starts with: 
<pre><code>
---------------------------------------------------------------------------
Process:               iscsid [68]
Path:                  /Library/PrivilegedHelperTools/iscsid
Identifier:            iscsid
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
Responsible:           iscsid [68]
User ID:               0

Date/Time:             2016-02-15 18:33:25.529 +0100
OS Version:            Mac OS X 10.11 (15A284)
Report Version:        11
Anonymous UUID:        B3B11DCF-F07D-5927-5F8E-F626ECE8D1FA

Time Awake Since Boot: 6 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x8:
--> 
    __TEXT                 000000010e104000-000000010e116000 [   72K] r-x/rwx SM=COW  /Library/PrivilegedHelperTools/*

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation            0x00007fff9a5ca5fe CFRunLoopAddSource + 78
1   iscsid                              0x000000010e108479 iSCSIInitialize + 52
2   iscsid                              0x000000010e10a61b main + 672
3   iscsid                              0x000000010e10587c start + 52
---------------------------------------------------------------------------
</code></pre>

Hope this helps,

Regards,

  Manuel Martínez

**Comment by nsinenian** [comment]
Hi Manuel,

I believe that the last few commits in the develop branch should address this problem. Please try it out and let know what you find.

Thank you!
