### ISSUE TITLE
Login to target - nothing happens

### ISSUE THREAD

**Issue by patrickchoi** [iscsi-osx/iSCSIInitiator#43]
Seems I managed to get the targets setup, but when I try to use the login command, nothing happens. Tried it with sudo and without, but list luns doesn't return anything. 

Some example commands, happy to upload more if needed!

![screen shot 2016-03-14 at 12 18 37 am](https://cloud.githubusercontent.com/assets/4400404/13729878/56a85402-e97a-11e5-8b2f-323e56c74e63.png)

**Comment by nsinenian** [comment]
The problem I see is that the single target that's defined has no portals associated with it.

Did you add these targets manually, or did you use discovery? 

If you added targets manually, can you please tell me what command you used to add it. If you used discovery, please type in `iscsictl list discovery-config` and provide the output.

Which build are you using - are you using the .dmg under releases, or did you build from the develop or master branch?

**Comment by patrickchoi** [comment]
I somehow managed to get it working, I rebooted into Recovery OS, ran the csrutil command and downloaded source, built using build.sh and now I can login. Originally I downloaded the DMG file and installed from there. 

However I'm getting a different problem now, I can get into the disk fine, but Finder doesn't want to play. Terminal commands are ok (i.e. ls), but once a Finder window is opened, it just sits there and spins. 

After 2-3 minutes, the Finder window disappears, and I have to run the login command again. The disk is unmounted. 

![screen shot 2016-03-14 at 12 57 58 am](https://cloud.githubusercontent.com/assets/4400404/13730071/f51d9e62-e97f-11e5-946f-0c1462f51df6.png)

**Comment by patrickchoi** [comment]
Here's a screenshot of the login output

![screen shot 2016-03-14 at 1 01 01 am](https://cloud.githubusercontent.com/assets/4400404/13730080/4df0ca0a-e980-11e5-9ba0-7f6ad39127c1.png)

**Comment by nsinenian** [comment]
I'll need to look at the iSCSI traffic between your machine and the NAS to figure out why it drops the connection. Please login, and once it logs out on its own provide the output for `sudo dmesg | grep iscsi`. In addition, please use `tcpdump` or wireshark to monitor and log iSCSI traffic just before you start login until it logs out. You can attach these outputs directly to the post (no need for screen caps). Thanks.

**Comment by patrickchoi** [comment]
I'm not familiar with tcpdump, but I think I managed to get both dmesg & wireshark. Droplink follows (wow it's big). Wireshark started just before login, and stopped a little bit after the disconnect. 

https://dl.dropboxusercontent.com/u/1382486/wireshark_dmesg.zip

**Comment by nsinenian** [comment]
@patrickchoi Can you please try beta 4 and let us know if this issue is resolved? Thanks!

**Comment by nsinenian** [comment]
@patrickchoi I'm merging this with issue ( #65 ). It appears to be the same problem. Can you please let me know what model Synology  you are using, and which DSM version?
