### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by devalios** [iscsi-osx/iSCSIInitiator#44]
Hi, I managed to run the install iSCSI.
it works great.
However, the auto-login does not work, does not attach itself only a manual start.
Before installing I turned off the csrutil disable.

However, this has not been run sudo nvram boot-args = kext-dev-mode = 1
Perhaps the reason?

**Comment by vlc1** [comment]
Hi Albert,

I'm having a similar issue, did you figure out how to get the auto-login to work? (see issue #56)

Thanks,
Vincent

**Comment by devalios** [comment]
It did not even work anymore! :)

**Comment by nsinenian** [comment]
@devalios @vlc1 Please move this discussion to issue #56
