### ISSUE TITLE
unable to format attached iscsi disk

### ISSUE THREAD

**Issue by Eveink** [iscsi-osx/iSCSIInitiator#45]
ServerSide: win server 2012r2 software target
ClientSide:
HyperMeow:~ root# iscsictl login iqn.1991-05.com.microsoft:svr01-share-target
Attached iqn.1991-05.com.microsoft:svr01-share-target <scsi domain 0, target 0>
    MSFT Virtual HD 6.3
    Serial Number 76741189-0F61-4F19-9AAB-4FAB80E2E1F6
    lun 0: type 0x00 (Block device)
HyperMeow:~ root# iscsictl list luns
iqn.1991-05.com.microsoft:svr01-share-target <scsi domain 0, target 0>
    MSFT Virtual HD 6.3
    Serial Number 76741189-0F61-4F19-9AAB-4FAB80E2E1F6
    lun 0: type 0x00 (Block device)
        disk5: 10.74 GB (20971520 512 byte blocks)
diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            120.5 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           +120.1 GB   disk1
                                 Logical Volume on disk0s2
                                 AE08F4BD-3565-44B8-86E4-3B151F4264F7
                                 Unlocked Encrypted
/dev/disk2 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *128.7 GB   disk2
   1:               Windows_NTFS Transcend               128.7 GB   disk2s1
/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                                                   *10.7 GB    disk3
HyperMeow:~ root# diskutil eraseDisk JHFS+ test GPT disk3
Started erase on disk3
Unmounting disk
......hang on a very long time........

**Comment by nsinenian** [comment]
1. Are you able to connect to the target with an iSCSI initiator on Windows? 
2. Can you please send a `tcpdump` or Wireshark trace showing iSCSI traffic between the two?

**Comment by henryxwong** [comment]
Same issue here

#diskutil eraseDisk JHFS+ iSCSI /dev/disk2 
Started erase on disk2
Unmounting disk
Error: -69888: Couldn't unmount disk


I tried both Disk Utility and diskutil command.

**Comment by nsinenian** [comment]
Please try the latest commit (dfc2f94) on the develop branch. This may have been fixed.

I have been able to reproduce your problem using a corner case of the negotiated iSCSI parameters,but I cannot verify that this applies to you since I don't have your iSCSI traffic dump.

Please let me know if it works.
