### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by domisol** [iscsi-osx/iSCSIInitiator#5]
Trying to compile (OsX 10.9.5 / XCode 6.2), I find the following issues :+1: 
Kernel/crc32c.c
Kernel/crc32c.c:197:42: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'uint32_t' (aka 'unsigned int')
Kernel/crc32c.c:198:42: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'uint32_t' (aka 'unsigned int')
Kernel/crc32c.c:217:43: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'uint32_t' (aka 'unsigned int')
Kernel/crc32c.c:218:43: Implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'uint32_t' (aka 'unsigned int')

Kernel/iSCSIVirtualHBA.cpp
Kernel/iSCSIVirtualHBA.cpp:470:40: Format specifies type 'int' but the argument has type 'UInt64' (aka 'unsigned long long')
Kernel/iSCSIVirtualHBA.cpp:1761:53: Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'UInt32' (aka 'unsigned int')

Hope this helps :-)

Jean-David

**Comment by Eveink** [comment]
same issue.(xcode 6.3.1)

**Comment by bktay** [comment]
The main question is why uint64_t was deemed necessary in the first place. From reading the code, it would appear that uint32_t would suffice.

**Comment by nsinenian** [comment]
These are compiler warnings, not errors.  The code should compile (as verified by several people) unless you have strict settings in Xcode where warnings are treated as errors.  As for the uint64_t, that discussion belongs in another thread.  The crc32q instruction (used in that code) requires 64-bit inputs.
