### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by BestMacsBen** [iscsi-osx/iSCSIInitiator#50]
On 10.11.5 and Xcode 7.3.1 (7D1014), some components fail to build. The resultant .pkg only had the framework and was missing everything else, failing the pkg's post install. 

If I run the project from Xcode, it says it succeeds but a subsequent run on the script has the same result. Attached is the output from the script.
[failed build.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/287595/failed.build.txt)

**Comment by nsinenian** [comment]
Give it another try (develop branch). Xcode seems to handle changes to project settings a bit different when it comes to git commits, so the project settings (including the new build schemes) were not pushed while everything else was.

**Comment by BestMacsBen** [comment]
That worked, thanks!
