### ISSUE TITLE
ISCSi-Beta2 crashes under El Capitan 10.11.6 Beta

### ISSUE THREAD

**Issue by yabba235** [iscsi-osx/iSCSIInitiator#51]
Hi !
Under OS X 10.11.6 any option add to terminal command iscsictl ( eg. iscsictl add target xxxx ) resuls crash app.
I attach error report.
Reg.
[error raport.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/287617/error.raport.txt)

**Comment by nsinenian** [comment]
Let me know if the DMG below fixes this problem (add a DMG extension to the file)

[iSCSIInitiator-1.0.0-beta2+++.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/321550/iSCSIInitiator-1.0.0-beta2.txt)
