### ISSUE TITLE
iscsictl not responding/crashing on El Capitan

### ISSUE THREAD

**Issue by rosstex** [iscsi-osx/iSCSIInitiator#52]
On OSX 10.11.5 El Capitan, running most commands with 'sudo' results in the error `Trace/BPT trap: 5`.

```
rteixeira-mbp:~ rteixeira$ iscsictl list targets
Trace/BPT trap: 5
rteixeira-mbp:~ rteixeira$ iscsictl add target blah
iscsictl: A target must be specified using a valid IQN or EUI-64 identifier
Trace/BPT trap: 5
```
Running iscsictl with 'sudo' prevents the error, but it still looks like nothing is happening.

```
rteixeira-mbp:~ rteixeira$ sudo iscsictl list targets
rteixeira-mbp:~ rteixeira$ sudo iscsictl add target <valid iqn>,<valid ip>
rteixeira-mbp:~ rteixeira$ sudo iscsictl list targets
rteixeira-mbp:~ rteixeira$
```

**Comment by nsinenian** [comment]
Let me know if the DMG below solves the problem (add DMG extension to the file)

[iSCSIInitiator-1.0.0-beta2+++.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/321549/iSCSIInitiator-1.0.0-beta2.txt)

**Comment by nsinenian** [comment]
Also, please note that sudo is no longer required. The OS X authorization DB is used to allow/prevent access to operations. See [Managing User Rights](https://github.com/iscsi-osx/iSCSIInitiator/wiki/Managing-User-Rights) in the wiki.

**Comment by mjoe** [comment]
@nsinenian yes it does, at least on my machine
`ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34`

**Comment by rosstex** [comment]
Thanks, that seemed to fix it!

**Comment by nsinenian** [comment]
Beta 3 was just posted, it is based on the release I attached on to this thread (with additional fixes). If you find that this issue persists with beta 3 please re-open this thread.
