### ISSUE TITLE
Crash when trying to manually add a target with a portal that has an IP under 10 bytes in length

### ISSUE THREAD

**Issue by zazard** [iscsi-osx/iSCSIInitiator#55]
Hello,

Running on OSX 10.11.3 (15D21)
The following command gives out a segmentation fault (Both in the latest release and the latest github code):
`iscsictl add target iqn.2016-08.local.domain:test,10.54.1.4`

While debugging, I managed to locate the error in User/iSCSI Framework/iSCSIUtils.c, line 106:
```
if(regexec(&preg,CFStringGetCStringPtr(portal,kCFStringEncodingASCII),maxMatches[index],matches,0)) {
[...]
}
```

The call to CFStringGetCStringPtr(portal,kCFStringEncodingASCII) apparently returns NULL for portal IPs under 10 characters long.

The error is fixable by converting the CFStringRef "manually" using CFStringGetCString with a preallocated buffer, instead of using CFStringGetCStringPtr. (According to the [Apple Developer Docs](https://developer.apple.com/reference/corefoundation/1542133-cfstringgetcstringptr?language=objc) (Bottom of the page), CFStringGetCStringPtr is not guaranteed to return non-NULL, and must be "backed up" by a call to CFStringGetCString in that case.)

I genuinely have no idea WHY this would happen, but, hey, it does ! I will attempt to go and fix this potential error everywhere in the code where there's a call to CFStringGetCStringPtr, and make a pull request, but a bit later, as for now I'm calling it a day. Just thought you should know :)

**Comment by nsinenian** [comment]
Yep. I discovered the fine print on CFStringGetCStringPtr many months ago and I thought I changed most if not all of the instances, but it appears that I have missed quite a few. It's a convenience function that is mostly useless, so it's a pointless thing to have in one's API IMO.

If you get a chance please go ahead and make the changes (to the develop branch) - you'll see how I've done them if you look back at past commits. If I get to it first it I'll close out the issue and let you know.

**Comment by zazard** [comment]
I may have been too hasty saying that this is the actual cause of the problem - See pull request, I replaced every occurence of CFStringGetCStringPtr but I still have the problem in some configurations. Will investigate further.

**Comment by zazard** [comment]
Seems all OK now - My fault, I'm not yet very used to debugging native OSX apps. The problem is indeed fixed.

**Comment by nsinenian** [comment]
I merged your changes after resolving conflicts, so we should not have the problem any more (on develop). Thanks for your contribution.
