### ISSUE TITLE
Unable to mount ReadyNAS 4.2.28 iSCSI LUN using b4

### ISSUE THREAD

**Issue by GJSchaller** [iscsi-osx/iSCSIInitiator#63]
I'm running Beta 4 on an iMac running El Capitan (10.11.6 with all updates as of September 6th, 2016).  I was able to install the package without issue, and it took me a bit to find the name of the iSCSI target (it took a Windows PC, natch), but I finally got it.

The first time I attached, I saw a 2 MB drive appear for a brief moment - even though the LUN is 2 TB in size.  Now, when I try to attach to the LUN, I am unable to.  The following are the commands I use and their output:

Last login: Wed Sep  7 20:23:50 on console
Harlock-House-iMac:~ gjschaller$ iscsictl list targets
iqn.2016-09.GeoffNAS.com:itunesdata <inactive, static>
	10.0.0.254 <inactive, port 3260, interface default>
Harlock-House-iMac:~ gjschaller$ iscsictl login iqn.2016-09.GeoffNAS.com:itunesdata,10.0.0.254
Harlock-House-iMac:~ gjschaller$ iscsictl list targets
iqn.2016-09.GeoffNAS.com:itunesdata <inactive, static>
	10.0.0.254 <inactive, port 3260, interface default>
Harlock-House-iMac:~ gjschaller$

I can see the target, logging on does not produce a result, or an error.

**Comment by GJSchaller** [comment]
Log is attached.

[iscsid_2016-09-07-202355_Harlock-House-iMac.crash.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/460612/iscsid_2016-09-07-202355_Harlock-House-iMac.crash.txt)

**Comment by nsinenian** [comment]
1. Has it ever worked? (any other version of this initiator? If so, which ones?)
2. I'm afraid that the crash log isn't terribly helpful. Please use wireshark to collect traffic between your PC and the NAS during login the very first time (reboot your machine, start wireshark and then do a login - let the 2MB LUN appear and disappear, wait a few minutes then save the traffic and send it over).

**Comment by GJSchaller** [comment]
I've only ever used this version - this is my first attempt (I was happy to see b4 had just come out when I discovered it!).

Logs attached.  Here's the console:

Last login: Thu Sep  8 18:07:52 on console
Harlock-House-iMac:~ gjschaller$ iscsictl login iqn.2016-09.GeoffNAS.com:itunes,10.0.0.254
Harlock-House-iMac:~ gjschaller$ iscsictl list target-config iqn.2016-09.GeoffNAS.com:itunes
iqn.2016-09.GeoffNAS.com:itunes <inactive, static>
	node-alias: <unknown>
	auto-login: disabled
	persistent: yes
	Configuration:
		MaxConnections (1)
		ErrorRecoveryLevel (0)
		HeaderDigest (none)
		DataDigest (none)
	Authentication: none
		CHAP-name 
		CHAP-secret <unspecified>
	10.0.0.254 <inactive, port 3260, interface default>
Harlock-House-iMac:~ gjschaller$ 

[iSCSICTL-WireShark.pcapng.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/462805/iSCSICTL-WireShark.pcapng.zip)

**Comment by nsinenian** [comment]
I don't see any iSCSI traffic in the capture (not even a login request), and it's strange that the login command doesn't actually return anything (it usually returns an error if something's wrong).

Can you give me the output of "ioreg | grep iscsi", and the output of "ls -l /var/run/iscsid" ?

**Comment by GJSchaller** [comment]
Will do - going to be away for a few days, will do when I am back.

**Comment by GJSchaller** [comment]
Last login: Thu Sep  8 18:09:16 on ttys000
Harlock-House-iMac:~ gjschaller$ ioreg | grep iscsi
Harlock-House-iMac:~ gjschaller$ ls -l /var/run/iscsid
srw-rw-rw-  1 root  daemon  0 Sep  8 18:07 /var/run/iscsid
Harlock-House-iMac:~ gjschaller$ 

Note that nothing was returned for the first command, at all.

**Comment by nsinenian** [comment]
Sounds like it isn't installed properly. Did you follow instructions to
disable system protection as described on the project home page *prior* to
installation?

**Comment by GJSchaller** [comment]
I thought I had, but can double check.  Will an uninstall / reinstall work, or are other steps needed?

**Comment by nsinenian** [comment]
Uninstall using the uninstall package in the DMG, run the commands
(csrutil... from the recovery console ) that will require 2 reboots I
believe and install again. If the output to "ioreg..." is still missing the
then the kext has not been loaded by the OS.

**Comment by GJSchaller** [comment]
OK, got it - now doing much better, but still not connecting.  Now seeing:

Harlock-House-iMac:~ gjschaller$ iscsictl list discovery-config
SendTargets: enabled
	interval: 30 seconds
	discovery-portals: 1
		10.0.0.254      <port 3260, interface default>
Harlock-House-iMac:~ gjschaller$ iscsictl login iqn.2016-09.GeoffNAS.com:itunes,10.0.0.254
iscsictl: Target services unavailable
Harlock-House-iMac:~ gjschaller$ ioreg | grep iscsi
      +-o com_github_iscsi_osx_iSCSIInitiator  <class com_github_iscsi_osx_iSCSIInitiator, id 0x10000050c, registered, matched, active, busy 0 (1 ms), retain 6>
        +-o com_github_iscsi_osx_iSCSIVirtualHBA  <class com_github_iscsi_osx_iSCSIVirtualHBA, id 0x10000050d, registered, matched, active, busy 0 (0 ms), retain 6>
          +-o com_github_iscsi_osx_iSCSIHBAUserClient  <class com_github_iscsi_osx_iSCSIHBAUserClient, id 0x10000050e, !registered, !matched, active, busy 0, retain 6>
Harlock-House-iMac:~ gjschaller$ ls -l /var/run/iscsid
srw-rw-rw-  1 root  daemon  0 Sep 11 20:39 /var/run/iscsid
Harlock-House-iMac:~ gjschaller$ 

+++

I have enabled CHAP and configured it on both the iMac and the NAS, and I have configured the NAS to allow the iMac's IQN.

**Comment by nsinenian** [comment]
The message "Target Services Unavailable" suggests that everything is "working" as it should be - this is a message returned by the target. I'd suggest disabling CHAP and IQN restrictions and trying again.  Did you ensure that the initiator IQN is configured properly?

You can also view the traffic using Wireshark to see what the target responds with and attach the iSCSI traffic during login if it still doesn't work.

**Comment by GJSchaller** [comment]
Hm.  I checked all the configs, rebooted... and the kext failed to load again.  It seems even if it works, on rebooting it goes way and I need to re-enable it.

I also realized that moving my iTunes data to an iSCSI LUN was foolish, as the network share it's on feeds my Sonos system at home... so there's no point in me setting up the LUN any more.  I don't need to pursue this on my end.

If you want me to try and help debug why the kext keeps unloading, I can, otherwise go ahead and close out this issue.

**Comment by nsinenian** [comment]
I'd suggest closing the issue, the debug mode that allows for kext to be
loaded is temporary until we hit 1.0. Also, in 700 downloads or so this is
the first report so I don't think its a major issue at this point (I'd be
more concerned with a signed kext). Thanks!
