### ISSUE TITLE
el capitan issue ?

### ISSUE THREAD

**Issue by 20972097** [iscsi-osx/iSCSIInitiator#64]
Im having problems connecting to a Qnap target , i managed to get it working with yosemite but upgraded to el capitan and it now no longer works :(

My first issue is 

```
OS X 10.11 and later

Run the following command at the Recover OS terminal window:

csrutil enable

```

Should this be enable or disable ?

Secondly after adding a target and specifiying CHAP credentials i try to login

i get the following error

Unknown error: 268435459

Any help please :dancer:

**Comment by nsinenian** [comment]
As outlined in the README, it is "disable" and not "enable"

You will need to disable system protection and then re-install the initiator for it to work.

**Comment by 20972097** [comment]
Thanks for the info , I re-enabled it again and enabled it and then disabled it and it now works .

The problem i have now is getting auto login to work . No drive is mounted at login :(

the login and logout commands work perfect , its just trying to mount the drive at login using

sudo iscsictl modify target-config <target> -auto-login enable

the command works fine and i can see that " auto-login: enabled " is valid on the target , but nothing autologs in ?

**Comment by broncobenshea** [comment]
I with auto login enabled if I log out of user and log back in the drive will mount. however, if i restart or shut down, upon login the drive will not mount and has to be added again by iscsictl login command

**Comment by nsinenian** [comment]
@broncobenshea @20972097  I'm closing this thread because we have another one going  (#66) on auto-login specifically. Stay tuned for updates.
