### ISSUE TITLE
macOS Sierra: Synology DS214/215/DS1511 (SYNCHRONIZE_CACHE timeout)

### ISSUE THREAD

**Issue by IMEIICCID** [iscsi-osx/iSCSIInitiator#65]
Hi nsinenian,

I did grab the Code 1.0.0-beta4 and did compile it
on macOS Sierra 10.12 GM. Xcode 8.0

After login, mounting, my old ISCSI drive get’s recognized.

But it shows no data, which should be on the drive. 
After a while the drive will be automatically unmounted. 

I did: 
iscsictl modify initiator-config -node-name iqn.2000-01.com.localhost:initiator
iscsictl add target 
iqn.2000-01.com.synology:DiskStation.Target-1.df5c1c7695,192.168.123.4:3260
###### 

MacPro:~ tom$  iscsictl login iqn.2000-01.com.synology:DiskStation.Target-1.df5c1c7695
Attached iqn.2000-01.com.synology:DiskStation.Target-1.df5c1c7695 <scsi domain 0, target 0>

```
Serial Number n/a
lun 0: type 0x00 (Block device)
```

MacPro:~ tom$ diskutil list

/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *107.4 GB   disk3
   1:                        EFI EFI                     209.7 MB   disk3s1
   2:                  Apple_HFS ISCSI                   107.0 GB   disk3s2
###### 

 sudo dmesg | grep iscsi >

> iscsi: Transfer size: 536 (sid: 0, cid: 0)

iscsi: Transfer size: 315928 (sid: 0, cid: 0)
iscsi: Queued task 0xa1 (sid: 0, cid: 0)
loginwindow is not entitledUserEventAgent is not entitlediscsi: Task timeout for task 0x99 (sid: 0, cid: 0)
iscsi: Connection timeout (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Bytes per second: 19078187 (sid: 0, cid: 0)
iscsi: Deactivated connection (sid: 0, cid: 0)
iscsi: Transfer size: 324120 (sid: 0, cid: 0)
iscsi: Queued task 0xa2 (sid: 0, cid: 0)
iscsi: Releasing session (sid 0)
iscsi: Removed event sources (sid: 0, cid: 0)
iscsi: Released connection (sid: 0, cid: 0)

Is this a Sierra problem?

**Comment by nsinenian** [comment]
It has not yet been tested with Sierra. If it worked in El Capitan (even with Beta-3), it's likely some compatibility issue with Sierra. I will start testing with Sierra soon. In the mean time, can you provide the iSCSI traffic between your machine and the NAS? (e.g. using Wireshark?) 

It looks like there's a timeout (e.g., NAS doesn't respond to some initiator command). It would be good to figure out what's going on.

**Comment by IMEIICCID** [comment]
I will come up with Wireshark log soon.
I need to install this and I have to get familiar with this software. 
So you need "iSCSI PDUs going back and forth" I will send it later.

I did make another try.
Could it be a problem with „Synology NAS“ ?

I did install now Beta4 in virtual machine (Parallels Desktop) 
Mavericks 10.9.3 and I got same issue.

So I also did create a new Target and LUN to test.
I could than initialize a new disc in Mavericks VM.
I did format this volume but can’t be activated than.

Yes it would be good to figure out this error.

**Comment by IMEIICCID** [comment]
in Wireshark what Filter do I need?

**Comment by nsinenian** [comment]
The iSCSI filter should be sufficient. Make sure you capture packets before login, and up to timeout. That way we’ll be able to figure out what’s causing the timeout and dropped session.

**Comment by IMEIICCID** [comment]
So I did it  https://dl.dropboxusercontent.com/u/2598295/iscsi-wireshark.pcapng
I did capure before iscsictl login and until the forced unmount.

**Comment by IMEIICCID** [comment]
nsinenian ,  can you use this log?

**Comment by nsinenian** [comment]
@IMEIICCID The logs show that your NAS stop responding to a SCSI request (SYNCHRONIZE_CACHE command). The SCSI request is generated by mac OS, not by the initiator. The initiator simply wraps the commands into iSCSI packets and sends them along. So there's nothing wrong with the initiator per se, but unlike other initiators it relies not the OS X SCSI stack and there may be some compatibility issue with between that stack and your NAS. 

Other Synology users (Synology Diskstation users) are not experiencing this issue, so I wonder what differences there are between your model an other users. Can you please give the model number of your NAS?

**Comment by IMEIICCID** [comment]
Hi nsinenian ,
thank you for evaluate the log file.
I thought so too because evan on Maverricks it did not work.

I've got the DS215j , DSM 6.0.2-8451 Update 1

**Comment by DDAAXX** [comment]
Hi,
I have exactly the same problem with a DS214 with latest DSM.
Do you have any hint?

**Comment by DDAAXX** [comment]
With the evaluate version of Daemon Tools, I can correctly mount my iSCSI drive, so I don't think the problem is linked to the Synology NAS.
This morning I've been able to see once the content of my iscsi disk, but when I tried to open a file, the drive unmounted.
What can I do to debug deeper this kind of problem?

**Comment by nsinenian** [comment]
Assuming the actual cause of your problem is the same as the original post
in this thread, then the problem is likely a combination of the OS X SCSI
stack (or a parameter setting in this stack) and your particular model.
For some reason, other Synology products (e.g., the DS6xx) seem to be
working fine.

I suggest using Wireshark to capture iSCSI packets from the point of login
until unmount/drop.  That way we can evaluate the root cause of the problem.

**Comment by DDAAXX** [comment]
Thank you for your reply.
This afternoon I will capture with WireShark and post here the result.

**Comment by IMEIICCID** [comment]
meanwhile I have success with http://www.kernsafe.com/product/macos-iscsi-initiator.aspx
I think every Diskstation with latest DSM is fine.
There must be a bug in iSCSIInitiator.

**Comment by DDAAXX** [comment]
But Kernsafe is not free, isn't it?

**Comment by IMEIICCID** [comment]
1  iSCSI target can connect to  is Free but I did not figure out how to automount

**Comment by nsinenian** [comment]
@IMEIICCID I don't think it is a bug in the iSCSI initiator.

The code that makes up the initiator consists of two parts: the part that
is posted here on GitHub, and the part that comprises the Mac OS SCSI stack
(Apple's code). The initiator posted here simply translates between the OS
and your NAS.  The translation is not the problem, as shown by the
Wireshark dump you posted. The NAS doesn't response to a specific SCSI
command, which is sent by the OS. This isn't something we have control over
in the iSCSI code.

There are some adjustable parameters in the SCSI stack, and it is possible
that changing some of these may fix the problem.  But I do not believe that
it is the code itself.

KernSafe and others may use a different implementation. For example, they
might bypass the OS X's SCSI stack entirely.  For simplicity and
compatibility with future versions of OS X, the decision was made to re-use
as much of the existing SCSI code from the OS as possible.

**Comment by IMEIICCID** [comment]
actually, I would prefer iSCSIInitiator 1.0.0-beta4 because I can work with scripts to automount for example. 
In the meantime I need to use Kernsafe solution to reach my DATA.

**Comment by nsinenian** [comment]
Assuming @DDAAXX has the same problem (NAS doesn't like the
SYNCHRONIZE_CACHE command) we can detect when the OS tries to send that
command and throw it away, to see if that addresses the issue. Not sure
what kind of impact that will have on the data integrity or NAS. I will
have to research that, and maybe we can generate a build for you both to
test.

**Comment by IMEIICCID** [comment]
I did write yesterday a support resume to Synology. Maybe they are interessted to help solve the problem. But answer from Synology takes forever.

**Comment by nsinenian** [comment]
@IMEIICCID  Another thought - using KernSafe, for example, can you capture iSCSI packets to see if a SYNCHRONIZE_CACHE is ever sent, or if the NAS responds? It would be helpful I think if you can obtain that and post it here.

**Comment by IMEIICCID** [comment]
Wireshark Logon with Kernsafe
https://dl.dropboxusercontent.com/u/2598295/lognon-kernsafe-ISCSI.pcapng

**Comment by IMEIICCID** [comment]
Thank you nsinenian ! I will test the new build

**Comment by nsinenian** [comment]
Try the attached build. It basically ignores OS requests for SYNC_CACHE and tells the OS that the command was successfully executed. If this works, I suspect there is something likely wrong with Synology's implementation on certain models (it probably uses one of two or three standard Linux targets). The command is part of the SCSI standard so these units should in theory support it.

Change the file extension from ZIP to DMG and install as usual (uninstall first, install, and reboot before trying).


[iSCSIInitiator-1.0.0-beta4_NO_SYNC.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/511792/iSCSIInitiator-1.0.0-beta4_NO_SYNC.zip)

**Comment by IMEIICCID** [comment]
Yes this one works! Thank you so much!
As user it say's "Could not connect to iscsid."
So let it run as root, than it works.

**Comment by DDAAXX** [comment]
With Sierra is not working.
The drive mounts and shows me files, but when I try to open iPhoto to use the archive stored on iscsi, the drive disconnect.

**Comment by nsinenian** [comment]
@DDAAXX Can you attach another Wireshark capture from login to disconnect (after you open iPhoto?) Perhaps you have a different problem...

**Comment by nsinenian** [comment]
@IMEIICCID Good to know its working. Please test it out for a couple of weeks and let me know if there are any data integrity issues. We'll have to come up with a way of detecting and disabling this for NAS units that do not support the command (I do not want to disable it for everyone).

**Comment by DDAAXX** [comment]
@nsinenian sorry, I did a mistake.
This morning I uninstall/install your software, and now it's working!!!
At this moment it's working at home, updating iPhoto library with iCloud photo.
When I'll come back at home this evening I'll check if everything's ok at all.
Thanks a lot for your work!

**Comment by IMEIICCID** [comment]
@nsinenian it is working also under Sierra 10.12.0 
I i preciate your work. Thanks again.

**Comment by IMEIICCID** [comment]
@nsinenian 
The ISCSI volume is ejected after about 30 minutes.
Do you have any hint?
https://dl.dropboxusercontent.com/u/2598295/iscsi.log

**Comment by nsinenian** [comment]
30 minutes is the timeout for certain tasks. It may be similar to the SYNC
problem but another command that the NAS never acknowledges.

Can you capture packets during a timeout? It should be reproducible - when
it gets close to 30 minutes just save the traffic.

**Comment by IMEIICCID** [comment]
Yes of course
https://dl.dropboxusercontent.com/u/2598295/iscsi-logout.pcapng.gz

**Comment by DDAAXX** [comment]
With this latest version, when I try to login I have this error:
iscsictl: Unknown error: 268435459

**Comment by IMEIICCID** [comment]
@nsinenian 
thank you for the update.  It seems to work so far.
I'll test the software and give you feedback.

**Comment by DDAAXX** [comment]
I reinstalled twice and now also for me is working.
Some strange things... after another reboot, I had the same Unknown error.
Then I rebooted and now it is correctly mounted.

Now I check if it unmount in 30 minutes as the other release.

**Comment by DDAAXX** [comment]
It seems to be quite stable.
I'm using it without problem since I posted before, no disconnection at all.
@nsinenian thank you so much!!!

**Comment by nsinenian** [comment]
@DDAAXX @IMEIICCID  There are three main iSCSI targets available for linux, and I know that Synology uses either IET or LIO. I need to know which one your devices are using so I can determine which implementation has this problem (it may affect other NAS products that use the same iSCSI target).

One way for me to get this information is for you to run "iscsictl list luns"  after login and tell me if you see anything that may look like "IET" or "LIO" and let me know. Can you please try this? It may simply show "Synology", but I think it's worth a try.

**Comment by IMEIICCID** [comment]
@nsinenian 
There is no „iscsictl“ 
I only found:
#########################
iscsi-iname
iscsi_snapshot_comm_core  
iscsi_snapshot_server     
iscsiadm
iscsid
iscsischsnaptool  

#########################

sh-4.3# iscsiadm -m session  -P 3
iSCSI Transport Class version 2.0-870
version 2.0-871
iscsiadm: No active sessions.
Does this help?

**Comment by DDAAXX** [comment]
@nsinenian , I've just checked the dmesg log of my Synology NAS, and I found something connected to the backup of my iscsi partition that give me the idea this is a LIO target.
LUN-Backup: thread name LIO_Bkp_f_1

**Comment by nsinenian** [comment]
@DDAAXX helpful, thanks! Can you also provide the output of "uname -a" (kernel version) on your Synology NAS?

**Comment by DDAAXX** [comment]
@nsinenian, here the uname result:
Linux DiskStation 3.2.40 #8451 Wed Aug 17 05:12:07 CST 2016 armv7l GNU/Linux synology_armada370_214se

**Comment by nsinenian** [comment]
@DDAAXX @IMEIICCID  It appears that Synology NASs can be configured for IET instead of LIO, which I believe should solve your problems. I'm not too familiar with Synology but I did see this post [on a forum (steps 1 - 6)](https://forum.synology.com/enu/viewtopic.php?t=19569#p120352) that walks through how to switch from LIO to IET.  There is also a Youtube video [here](https://www.youtube.com/watch?v=hoCDp-tnA_Q).

If you can, please try this out and use the original beta-4 release and let me know how it works out. I think this really is a LIO problem, and other initiators must have hard-coded in a workaround like I did for you - not the best thing to do since LIO really isn't adhering to the iSCSI standard (IET is much better).

**Comment by DDAAXX** [comment]
@nsinenian with the IET configuration and beta 4, I can see files on iscsi disk, but I have the disk disconnection as this issue start.
I than reinstall latest beta4 patched and I have the same correct functioning.
So LIO or IET have the same effect

**Comment by DDAAXX** [comment]
@nsinenian As side effect, with iet I cannot correctly perform iscsi lun backup, so I reverted to lio

**Comment by IMEIICCID** [comment]
@nsinenian 
I cant login to target not at all

iscsictl login iqn.2000-01.com.synology:DiskStation.Target-1.df5c1c7695
iscsictl: Unknown error: 268435459

I did  change support_iscsi_type="lio" to support_iscsi_type="iet" 

I did compile code Beta 4 on 10.12.0 GM - Xcode Version 8.0 (8A218a)
I've got some issues, maybe that the reason for error 268435459

**Comment by IMEIICCID** [comment]
@nsinenian  is there a compiled beta4 available?

**Comment by IMEIICCID** [comment]
@nsinenian 
with iet on DS215j and  iSCSIInitiator beta 4 
 iscsictl login iqn.2000-01.com.synology:DiskStation.Target-1.df5c1c7695
iscsictl: Input/output error

**Comment by nsinenian** [comment]
I can't be sure, but it sounds like Synology may be using older versions of IET/LIO. Current IET versions do not have the SYNCHRONIZE_CACHE issue (I am using IET), but I found that some early versions did not implement the command ([see for example this post](https://sourceforge.net/p/iscsitarget/mailman/message/8079892/)). Similarly, early versions of LIO had issues with the command as well ([see this patch that eventually fixed it](http://www.serverphorums.com/read.php?12,191963)).

Stick with LIO since that is supposed to be newer (integrated into the Linux kernel) and I suggest that you both file a report with Synology (I tried to contact them but they require a NAS serial number to fill out a support form which I do not have).  Other NAS models produced by Synology seem to be fine - for example the 412 appears to be working normally, so I would point that out and try to determine what differences there are between the Linux Kernels used in the 4xx and 2xx products.

**Comment by patrickchoi** [comment]
I'm using the Synology DS1511+ on the latest DSM (as of this post)

**Comment by nsinenian** [comment]
Synology has responded to my original request regarding this issue. I will keep you informed of any developments.

**Comment by DDAAXX** [comment]
@nsinenian thank you for your effort!

**Comment by nsinenian** [comment]
@DDAAXX  @patrickchoi  @IMEIICCID Can you guys please test this version for me - it is a different workaround that may sold your problem, and one I can keep moving forward (rename ZIP to DMG and install as usual)
[iSCSIInitiator-1.0.0-beta4++.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/628687/iSCSIInitiator-1.0.0-beta4.zip)

**Comment by DDAAXX** [comment]
Hi @nsinenian,
I tried it for a while, but it's quite unstable.
It works, but the volume fall down after some minutes and then I have to reboot my MacBook.

**Comment by nsinenian** [comment]
Can you send me a tcpdump (Wireshark) for this build, right through where
the volume drops?

**Comment by DDAAXX** [comment]
Sorry @nsinenian , for some days I will be out for work and I cannot do tests or logs.

**Comment by IMEIICCID** [comment]
@nsinenian  thank you very much for your new software.
I have been testing for a couple of hours. So far I've got no issues.

**Comment by nsinenian** [comment]
I believe this issue has been resolved since BETA5. If there are additional problems please open a new issue.
