### ISSUE TITLE
Unable to login in macOS Sierra, couldn't format in El Capitan

### ISSUE THREAD

**Issue by TychoAI** [iscsi-osx/iSCSIInitiator#67]
Hello,

first the important info:
- I am an iSCSI newb.
- attempting to use part of a Synology DS216j RAID 1 volume as an iSCSI target, formatted as block level
- computer is a "brand new" refurbished MacBook Air - Early 2015. Originally had El Capitan 10.11 and now running macOS Sierra
- using beta4 of the package installer

Original problem when running on El Capitan
- I was able to set up the LUN target for part of the RAID 1 volume on the Synology NAS, without CHAP.
- I used the package installed, turned off code signing, then installed and restarted. Turned off code signing then stumbled through the process of configuring discovery and listing the target.
- I was able to log into the target, at which point OS X immediately brought up the unknown format alert and invited me to format the target.
- This is where I got totally stuck. Attempting to format the newly found iSCSI Volume with Disk Utility wouldn't work. Upon starting the format, Disk Utility went to unmount the volume and it would just sit at that step. No error, just never actually unmounting. The computer was still running and could do other things, but would never format and could not restart or shut down graciously. A hard reboot was necessary each time I tried to get past this step.

Updated to macOS Sierra:
- turned off code signing and used the package uninstaller to remove
- re-installed from the package installer, restarted and re-enabled code signing
- Listing the targets still worked without having to reconfigure
- logging in to the target no longer works as per error below:

```

iscsictl login iqn.2000-01.com.synology:<NAS HOST>.Target-1.8e3a0bb317
iscsictl: Unknown error: 268435459
```

where `<NAS HOST>` is the name of my NAS

I understand that macOS Sierra hasn't been tested yet, but I assume it will. I'm hoping that it would somehow miraculously deal with the un-mounting problem

(as a side note, the point of trying to do this is to have fast access to a remote volume that's always connected and storing additional Photos libraries besides the current library on the main drive)

thanks

**Comment by nsinenian** [comment]
There are some developing issues with Synology DS2xx that we're trying to address. Stay tuned.

**Comment by TychoAI** [comment]
Any updates on this? At the last posting I "felt" like there would be something imminent, and held of trying the non-posted beta build from some other thread. Should I attempt that, or is there something coming soon?

Thanks again.

**Comment by nsinenian** [comment]
Please try this version (rename ZIP to DMG, install as usual): 
[iSCSIInitiator-1.0.0-beta4++.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/628688/iSCSIInitiator-1.0.0-beta4.zip)

**Comment by TychoAI** [comment]
Thank you, Nareg. This seems to have resolved the mounting issue. I uninstalled the previous build, installed this one and I was able to mount and format the iSCSI partition. Fantastic! This build does not auto-mount at login or after it goes to sleep. Using Sierra 10.12.1. I saw in a different thread you posted beta4+++. Is that something I should consider?

Many thanks,

**Comment by nsinenian** [comment]
Great. The build you are referring to specifically addresses auto-login. I am testing solutions one-by-one and then they will be aggregated together into the next release. The ‘+++’ build includes the build you just tested and additional fixes for auto-login. I am closing this thread - please comment on auto-login in the other thread.
