### ISSUE TITLE
CHAP authentication

### ISSUE THREAD

**Issue by Abdulabase** [iscsi-osx/iSCSIInitiator#68]
Hi,

I am using beta version 4 with macOS Sierra 10.12.
I am having some difficulty using Mutual CHAP authentication. The program works fine without CHAP, and with CHAP only (non Mutual CHAP). However, when I try using Mutual CHAP, I get an "authentication error". 

Now I suppose this should mean there is a problem with the authentication, i.e. the username/password is incorrect. However, I have checked these many times and they seem okay. I have enabled CHAP authentication for both the initiator and target, and as I have said it works fine without CHAP and with regular (if I can call it that) CHAP only.

P.S. Great program and very clear instructions. Well done and Thanks.

**Comment by nsinenian** [comment]
@Abdulabase Can you please open up the Keychain Access tool and verify that there is an entry with the name of the target to which you are trying to connect?

Can you please also send me the output from the Console tool (open the console tool and search for "iscsi" in the search field). Please do this right after you login (and get the "authentication error" message). Thanks!

**Comment by Abdulabase** [comment]
HI,
Sorry, I have been very busy. It worked fine when I tried again another time, I am no longer getting the error message. Yes there was an entry in Keychain Access, I tried to get the console tool output but I could not replicate the issue anymore. Thanks for the support.
