### ISSUE TITLE
Auto-login does not work in Sierra

### ISSUE THREAD

**Issue by vannman** [iscsi-osx/iSCSIInitiator#69]
Running 1.0.0-beta4 on MacOS Sierra version 10.12 the volumes are not mounted automatically after reboot. Instead I have to mount them manually using the iscsictl login command.

Here is the .plist:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/var/log/iscsid</string>
	<key>Sockets</key>
	<dict>
		<key>iscsid</key>
		<dict>
			<key>SockPathName</key>
			<string>/var/run/iscsid</string>
		</dict>
	</dict>
	<key>Program</key>
	<string>/usr/local/libexec/iscsid</string>
	<key>Label</key>
	<string>com.github.iscsi-osx.iscsid</string>
</dict>```

**Comment by nsinenian** [comment]
@vannman this is a known issue in macOS Sierra. I'm closing this because we already have an open issue regarding re-mount on wakeup (which is related to auto-login). See #66 for upcoming updates.
