### ISSUE TITLE
cannot load the kext

### ISSUE THREAD

**Issue by dalmata22** [iscsi-osx/iSCSIInitiator#7]
when i try and run the
###### #sudo kextload /tmp/iSCSIInitiator.kext
i receive this: 
###### /tmp/iSCSIInitiator.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).
form the console i can read:
###### 20/07/15 11:31:44,728 com.apple.kextd[44]: ERROR: invalid signature for com.github.iscsi-osx.iSCSIInitiator, will not load
I suppose the only way is run Kext in KEXT Development Mode, isn't it?

**Comment by bktay** [comment]
The short answer is yes

**Comment by nsinenian** [comment]
The README is now updated with these instructions.

**Comment by sparkrevolutions** [comment]
Hi, i'm still having problems with this.

Followed instructions to put it in Development Mode using the readme but Kext still wont load. Using Mavericks (10.9). When searching online, all instructions seem to be related to Yosemite - why is this?
