### ISSUE TITLE
iscsictl list target-config issue

### ISSUE THREAD

**Issue by ryansyah** [iscsi-osx/iSCSIInitiator#72]
I am not sure this command is functioning correctly, testing 1.0.0-Beta4+ build.
```
$ iscsictl list target-config
iscsictl: A target must be specified using a valid IQN or EUI-64 identifier
```

**Comment by nsinenian** [comment]
@ryansyah You need to specify a target name. See examples in the [Wiki](https://github.com/iscsi-osx/iSCSIInitiator/wiki/Target-configuration)

**Comment by ryansyah** [comment]
Thanks, I see that now and things are working as expected.
