### ISSUE TITLE
inactive target

### ISSUE THREAD

**Issue by broncobenshea** [iscsi-osx/iSCSIInitiator#73]
I am successfully able to add a target. When i display the target list it says that it is inacative. I enter command "$ iscsictl login <target>" and i get an "unknown error 268435459"
beta 4
os x 10.11.6

**Comment by nsinenian** [comment]
@broncobenshea Did you add the target manually? Please post the output of "ioreg | grep iscsi"

**Comment by broncobenshea** [comment]
iscsictl add target <target>,<portal> [-interface <interface>]
       iscsictl remove target <target>[,<portal>]
       iscsictl login  <target>[,<portal>]
       iscsictl logout <target>[,<portal>]
       iscsictl modify initiator-config [...]
       iscsictl modify target-config <target>[,<portal>] [...]
       iscsictl modify discovery-config [...]
       iscsictl list initiator-config
       iscsictl list target-config <target>
       iscsictl list discovery-config
       iscsictl add discovery-portal <portal> [-interface <interface>]
       iscsictl remove discovery-portal <portal>
       iscsictl list targets
       iscsictl list luns
I believe I added the target manually yes.

**Comment by broncobenshea** [comment]
How do I enable an inactive target? 
$ iscsictl list targets
iqn.2000-01.com.synology:iphoto <inactive, static>
	192.168.1.83 <inactive, port 3260, interface default>

thank you for your help! I really enjoy the simplicity of this tool.

**Comment by broncobenshea** [comment]
I fixed it. 
I was unclear that you first had to run the csrutil disable. that wasn't clear from the readme.

**Comment by nsinenian** [comment]
Glad it works. Thanks for catching the error in the read me it should be disable not enable.

Auto-login is a known problem there's another open thread.
