### ISSUE TITLE
Drobo B800i: (null) disk on macOS 10.12

### ISSUE THREAD

**Issue by takerukoushirou** [iscsi-osx/iSCSIInitiator#74]
After successfully discovering targets, configuring initiator CHAP and login into a target, no new device shows up and the LUN lists a "(null)" device:
```
$ iscsictl login iqn.2005-06.com.drobo:b800i.tXXXXXXXXXXX.id1
Attached iqn.2005-06.com.drobo: b800i.tXXXXXXXXXXX.id1 <scsi domain 2, target 0>
	Drobo B800i 1.00
	Serial Number XXXXXXXXXXXX
	lun 0: type 0x00 (Block device)
$ iscsictl list luns
iqn.2005-06.com.drobo: b800i.tXXXXXXXXXXX.id1 <scsi domain 2, target 0>
	Drobo B800i 1.00
	Serial Number XXXXXXXXXXXX
	lun 0: type 0x00 (Block device)
		(null): 2,2 TB (4294967160 512 byte blocks)
```

I get the same behaviour with both 1.0 beta 4, as well as building the latest sources myself. I get no error message and nothing seemingly wrong in the system log. 

Only when I then try to logout of the target, the command first hangs and then gives up with `iscsictl: Input/output error.` Again, nothing seems wrong in the system log:
```
Standard	22:58:48.796217 +0100	authd	Succeeded authorizing right 'com.github.iscsi-osx.iSCSIInitiator.login-logout' by client '/usr/local/libexec/iscsid' [4177] for authorization created by '/usr/local/bin/iscsictl' [4519] (3,0)
Standard	23:05:38.905053 +0100	kernel	iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Standard	23:05:38.905063 +0100	kernel	iscsi: Sending data length: 101
Standard	23:05:38.905761 +0100	kernel	iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Standard	23:05:38.906143 +0100	kernel	iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Standard	23:05:38.906149 +0100	kernel	iscsi: Sending data length: 284
Standard	23:05:38.906610 +0100	kernel	iscsi: Sent PDU type 0x43 (sid: 1, cid: 0)
Standard	23:05:38.907068 +0100	kernel	iscsi: Sent PDU type 0x44 (sid: 1, cid: 0)
Standard	23:05:38.907074 +0100	kernel	iscsi: Sending data length: 16
Standard	23:05:38.907866 +0100	kernel	iscsi: Deactivated connection (sid: 1, cid: 0)
Standard	23:05:38.907882 +0100	kernel	iscsi: Sent PDU type 0x46 (sid: 1, cid: 0)
Standard	23:05:38.908077 +0100	kernel	iscsi: Releasing session (sid 1)
Standard	23:05:38.908116 +0100	kernel	iscsi: Removed event sources (sid: 1, cid: 0)
Standard	23:05:38.908122 +0100	kernel	iscsi: Released connection (sid: 1, cid: 0)
```

macOS 10.12.1 (SIP disabled)
Initiator 1.0 beta 4
Drobo B800i with CHAP authentication target

**Comment by nsinenian** [comment]
Can you please capture traffic between your Drobo and your machine and post it here? You can use Wireshark to do so. That will help diagnose the problem.

**Comment by nsinenian** [comment]
Try the attached version and let me know if it addresses the problem
[iSCSIInitiator-1.0.0-beta4++.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/628692/iSCSIInitiator-1.0.0-beta4.zip)
 (rename ZIP to DMG and install normally):

**Comment by takerukoushirou** [comment]
Thank you very much, I will try this out as soon as possible. Unfortunately I currently do not have access to the Drobo and cannot test the new version nor capture the traffic. I'll let you know as soon as I was able to try it out.
