### ISSUE TITLE
Cannot change initiator IQN or alias

### ISSUE THREAD

**Issue by karlstevens** [iscsi-osx/iSCSIInitiator#75]
As per https://github.com/iscsi-osx/iSCSIInitiator/wiki/Initiator-configuration I am unable to change the initiator IQN.  I'm using 1.0.0-beta4 (dmg from github).

/Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist (where I assume the initiator IQN is stored) is not modified, and is not created if it is absent.  (In order to create it, I have to do portal discovery.)

osx2:nncd root# iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
        node-alias localhost
        Authentication: none
                CHAP-name localhost
                CHAP-secret <unspecified>
osx2:nncd root# iscsictl modify initiator-config -node-name iqn.2012-09.com.example:test
Initiator settings have been updated
osx2:nncd root# iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
        node-alias localhost
        Authentication: none
                CHAP-name localhost
                CHAP-secret <unspecified>
osx2:nncd root# iscsictl modify initiator-config -node-alias osx2test
Initiator settings have been updated
osx2:nncd root# iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
        node-alias localhost
        Authentication: none
                CHAP-name localhost
                CHAP-secret <unspecified>
osx2:nncd root# ls -l /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist
ls: /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist: No such file or directory
osx2:nncd root# iscsictl add discovery-portal 192.168.239.3 
The discovery portal 192.168.239.3 has been added
osx2:nncd root# ls -l /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist
-rw-r--r--  1 root  wheel  176 Nov 13 09:55 /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist
osx2:nncd root# iscsictl modify initiator-config -node-name iqn.2012-09.com.example:test
Initiator settings have been updated
osx2:nncd root# iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
        node-alias localhost
        Authentication: none
                CHAP-name localhost
                CHAP-secret <unspecified>
osx2:nncd root# ls -l /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist
-rw-r--r--  1 root  wheel  176 Nov 13 09:55 /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist

**Comment by nsinenian** [comment]
This issue has now been addressed (latest commit on develop). It will be incorporated into the next release. The problem was traced to a corner case where the IQN and alias are not updated when the user attempts to change these first (before modifying anything else).
