### ISSUE TITLE
QNAP: Connection dropped after 10 minutes

### ISSUE THREAD

**Issue by pierrezerbib** [iscsi-osx/iSCSIInitiator#76]
Two connexion with iscsi 4 stop after 10mn.

This connexion is with Qnap 4.10 

I look in log, but no information

**Comment by pierrezerbib** [comment]
Trace of log
Nov 23 12:49:50 iMac-de-pierre kernel[0]: iscsi: Task timeout for task 0x1ac33840 (sid: 0, cid: 0)
Nov 23 12:49:50 iMac-de-pierre kernel[0]: iscsi: Starting task 0x274ef4e0 (sid: 0, cid: 0)
Nov 23 12:49:50 iMac-de-pierre kernel[0]: iscsi: Sent PDU type 0x1 (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Task timeout for task 0x274ef4e0 (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Connection timeout (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Deactivated connection (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Releasing session (sid 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Removed event sources (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre kernel[0]: iscsi: Released connection (sid: 0, cid: 0)
Nov 23 12:50:10 iMac-de-pierre iscsid[2325]: TCP timeout for iqn.2004-04.com.qnap:ts-410:iscsi.imac2.c4bb1a over portal 192.168.111.152.

**Comment by pierrezerbib** [comment]
Why a tcp timeout, is it normal

**Comment by nsinenian** [comment]
There is a task timeout, which means that the initiator sent a command and received no response from the target. To better understand the problem, I will need you to capture TCP traffic between your machine and the target. You can do this using WireShark (www.wireshark.com). Please save the log and post it here. You should start logging before login, and stop logging after you see the TCP timeout.

**Comment by pierrezerbib** [comment]
This is a capture 
[iscsi.pcapng.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/609569/iscsi.pcapng.zip)

**Comment by nsinenian** [comment]
Try the attached version (rename ZIP to DMG and install normally): 
[iSCSIInitiator-1.0.0-beta4++.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/628686/iSCSIInitiator-1.0.0-beta4.zip)

**Comment by Muthuramane** [comment]
@nsinenian: In the trace log, I seen the host sending the SCSI command opcode 0x1b(Start Stop Unit) for LUN0 but target respond as Reject(Reason: Invalid PDU field) to the host.  To refer Frames 2735, 2736.
In Frame 2738, the target responded as FIN & ACK which means target closed the session but host initiator doesn't send FIN, ACK to target and also host sending the TUR to target in frame2762. 

In Frame 2763, the target responded [RST] to the host.

We have to take look at 
Why target responded as REJECT for opcode 0x1b?
Why host didn't close the session after receiving the FIN, ACK from target?

@pierrezerbib : Could you please collect target side log and look whether target supports SSU(0x1b) or not.

**Comment by nsinenian** [comment]
It has to do with the R/W flag set in the PDU that should have not been
set. The new build I posted here changes that, and that's what I wanted
Pierre to try out.

**Comment by nsinenian** [comment]
@pierrezerbib Did BETA-5 fix your problem? Please let me know.

**Comment by pierrezerbib** [comment]
where is possible to download Beta-5 ?

**Comment by nsinenian** [comment]
Same as all other BETA releases, under the releases page on GitHub: https://github.com/iscsi-osx/iSCSIInitiator/releases

**Comment by pierrezerbib** [comment]
Hi, it’s good actually.

Only Osx tell iscis down , but iscis up

**Comment by nsinenian** [comment]
I don't know what your second sentence means. Does it work, or not?

**Comment by pierrezerbib** [comment]
Sorry my english is bad.
My system indicates me that the iscsi record(disk) is to fall, but it is always and works

> 
>

**Comment by nsinenian** [comment]
No problem, thanks your testing and support.

**Comment by pierrezerbib** [comment]
Sorry I have an another problems, 
Actually on mac-mini El-capitan , iscsctl permission denied 

?
