### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by adlibdalom** [iscsi-osx/iSCSIInitiator#77]
Hello!

I'm getting `Permission denied` on most anything I do:
```
iscsictl add discovery-portal 10.0.0.5
iscsictl: Permission denied
---
iscsictl modify initiator-config
iscsictl: Permission denied
```
Here's perhaps something of interest:
```
ls -l /var/run/iscsid 
srw-rw-rw-  1 root  daemon  0 Dec  5 22:16 /var/run/iscsid
```

Am I missing something really basic? I've tried the commands with `sudo`, but that changes nothing. And from what I gather from previous issues, `sudo` shouldn't be required anylonger.
I'm on the `1.0.0beta4+++` "dev branch" and running macOS 10.12.1.

**Comment by nsinenian** [comment]
I don't think you're missing anything - this sounds like a corner case as others have not been reporting it. The permissions you have appear to be the same as they are on my system:

srw-rw-rw-  1 root  daemon     0B Dec  4 09:41 /var/run/iscsid

I'm wondering if things installed correctly on your system. Did the appropriate authorizations install into your authorizationdb? 

Do you get an output for the following command (won't affect your system):
security authorizationdb read com.github.iscsi-osx.iSCSIInitiator.modify-config

**Comment by adlibdalom** [comment]
I got this with that command:
```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>class</key>
	<string>rule</string>
	<key>created</key>
	<real>498335417.70902801</real>
	<key>default-prompt</key>
	<dict>
		<key></key>
		<string>For modifying initiator, discovery and target settings and adding and removing targets.</string>
	</dict>
	<key>identifier</key>
	<string>iscsid</string>
	<key>modified</key>
	<real>498335417.70902801</real>
	<key>requirement</key>
	<string>anchor apple generic and identifier iscsid and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = AXP58N43FN)</string>
	<key>rule</key>
	<array>
		<string>allow</string>
	</array>
	<key>version</key>
	<integer>0</integer>
</dict>
</plist>
YES (0)
```
Do you need anything else to troubleshoot this? Or do you want me to test anything else?
Thanks in advance!

**Comment by nsinenian** [comment]
This looks pretty normal. Can you verify that `iscsid` is running in activity monitor? Also, can you post your output of `ioreg | grep iscsi` - it should look something like this:

          +-o com_github_iscsi_osx_iSCSIInitiator  <class com_github_iscsi_osx_iSCSIInitiator, id 0x100000a03, registered, matched, active, busy 0 (1 ms), retain 6>
        +-o com_github_iscsi_osx_iSCSIVirtualHBA  <class com_github_iscsi_osx_iSCSIVirtualHBA, id 0x100000a04, registered, matched, active, busy 0 (0 ms), retain 6>
          +-o com_github_iscsi_osx_iSCSIHBAUserClient  <class com_github_iscsi_osx_iSCSIHBAUserClient, id 0x100000a05, !registered, !matched, active, busy 0, retain 6>

**Comment by adlibdalom** [comment]
Sorry for the delay in my answer. I just not ran the commands you asked, which actually is all blank!
`iscsid` is not running in Activity Monitor, and `ioreg | grep iscsi` gives no feedback what-so-ever.
What can be the cause of this? Is there a remedy?
Thanks again!

**Comment by adlibdalom** [comment]
I added `-i` to the grep command to search case insensitively, and four globalSAN iSCSI entries came up. I've since removed them (with their uninstaller), but there still is no sign of this product in the `ioreg` command. There's no `/var/run/iscsid` that the LaunchDaemon is pointing to, for example. There is however a `/Library/Frameworks/iSCSI.framework`.

**Comment by adlibdalom** [comment]
`ERROR: invalid signature for com.github.iscsi-osx.iSCSIInitiator, will not load` sounds like the main issue actually. Have I missed some crucial step?

**Comment by nsinenian** [comment]
It sound like you may have not have disabled SIP. Please see the
installation prerequisites and disable SIP to allow the OS to load the
unsigned extension. I would suggest reinstalling (install over) iSCSI after
you disable SIP.

**Comment by nsinenian** [comment]
It can be signed, except that (1) Apple charges for this (developer membership is required), despite the fact that it is an open-source project and distributed for free(!) (2) its an involved process and doesn't make sense to do on beta builds.
