### ISSUE TITLE
Benchmark Beta 5 under macOS Sierra 10.12.2 (16C67)

### ISSUE THREAD

**Issue by yabba235** [iscsi-osx/iSCSIInitiator#79]
Hi !
New beta 5 is still less able than the old beta 3 when it comes to reading, writing is better but only for files less than 4GB.
I give little results and outputs of the console:

Mac-mini-tb:~ tomek$ uname -a
Darwin Mac-mini-tb.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

Mac-mini-tb:~ tomek$ iscsictl login  iqn.2004-04.com.qnap:ts-453mini:iscsi.nowy.ea788f
Attached iqn.2004-04.com.qnap:ts-453mini:iscsi.nowy.ea788f <scsi domain 0, target 0>
	QNAP iSCSI Storage 4.0
	Serial Number e4d2f3c2-0cbb-48d4-8941-6fec2bfeb534
	lun 0: type 0x00 (Block device)
		disk2: 267,36 GB (65273856 4096 byte blocks)

aja test 

r/w 71/97 (256MB)
r/w 71/97 (512 MB)
r/w 71/95  (1GB)
r/w 68/67 (4GB)

Reg.
Tom

**Comment by serenissimo1** [comment]
On OSX 10.12.5 and macbookpro works fine. 
I have a Synology DS916+ and I want to thanks all the team to release this software. 
Very useful. Still difficult to understand why Apple didn't develop on her own.

**Comment by serenissimo1** [comment]
OSX 10.12.5 with a macbookpro and Synology DS916+ 
**aja test MB/s**

r/w 93/75 (512 Mb)
r/w 64/76 (1GB)
r/w 59/74 (4GB)
