### ISSUE TITLE
targets never come up

### ISSUE THREAD

**Issue by akohlsmith** [iscsi-osx/iSCSIInitiator#8]
$ sudo /tmp/iscsictl -targets

    +-o iqn.1995-05.com.seagate.mynas:iscsi2 [ Inactive ]
      +-o 192.168.0.107   [ Not Connected, Port:  3260, Interface: en0 ]

I can't seem to find a way to tell iSCSIInitiator to make the target active. 

I'm not sure if it's related, but discovering never works either:

    $ sudo /tmp/iscsictl -discovery -portal 192.168.0.107
    /tmp/iscsictl: Input/output error

Nothing interesting in the log nor dmesg.  This is OSX 10.10.3 with a Seagate 2 bay NAS.

**Comment by nsinenian** [comment]
I assume you tried the -login option?  What did iscsictl output?  Can you e-mail a tcp dump of the traffic between the initiator and target during login?
