### ISSUE TITLE
Unresponsive: No target-login possible after sleep on El Capitan. No network activity.

### ISSUE THREAD

**Issue by BjoKaSH** [iscsi-osx/iSCSIInitiator#80]
When accessing a target for login, no actual login (network traffic) is generated after return from sleep.

## Setup:

I installed the latest Beta5 on an almost fresh install of El Capitan (10.11.6).  I followed the instruction in the wiki.  SIP is disabled.

Machine is a "MacBook Pro (15-inch, Mid 2012)".
Target is an Ubuntu 16.04 server with the "iscsitarget" package as iscsi provider.  Output from the server's package description:
```
Package: iscsitarget                     
State: installed
Automatically installed: no
Version: 1.4.20.3+svn502-2ubuntu4
Priority: optional
Section: universe/net
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 175 k
Depends: libc6 (>= 2.14), procps, lsb-base (>= 3.2-14)
Recommends: iscsitarget-dkms
Conflicts: iscsitarget-source, iscsitarget:i386
Description: iSCSI Enterprise Target userland tools
 iSCSI Enterprise Target is for building an iSCSI storage system on Linux. It is aimed at developing an iSCSI target satisfying enterprise requirements. 
 
 This package contains the userland part; you require the kernel module for proper operation.
Homepage: http://iscsitarget.sourceforge.net/
```

Network access is by WiFi only.  No wired connection configured for the client (MacBook).  The server is on wired 1GB ethernet connected the the WiFi access point.

The box is multi-user, and login / logout is supposed to be run by all users (using a tiny wrapper script (bash) wrapped in an Automator "Program").

Tests done with users in the admin group and with unprivileged users.

Using "sudo" does not make any difference.

After install I could create a target definition, login and access the disk (initialise and use as TimeMachine volume).  All fine.

## Problem

After the system went to sleep and came back (closing the lid, opening after several hours again), iscsi became unresponsive.

Login times out after 30 seconds with error code 5
```
time /usr/local/bin/iscsictl  login iqn.2013-01.com.example:timemachine2,192.168.178.21 ; echo $?

real	0m30.133s
user	0m0.011s
sys	0m0.012s
5
```

Showing target configuration also stalls for about ten seconds before printing anything, then prints everything except the target line ("IP <inactive ...") and stalls another 20 seconds before completing the output:
```
time /usr/local/bin/iscsictl list target-config iqn.2013-01.com.example:timemachine2,192.168.178.21 ; echo $?
iqn.2013-01.com.example:timemachine2 <inactive, static>
	node-alias: 
	auto-login: enabled
	persistent: yes
	Configuration:
		MaxConnections (1)
		ErrorRecoveryLevel (0)
		HeaderDigest (none)
		DataDigest (none)
	Authentication: none
		CHAP-name 
		CHAP-secret <specified>
	192.168.178.21 <inactive, port 3260, interface default>

real	0m30.141s
user	0m0.018s
sys	0m0.011s
0
```

Neither trying to login nor listing the config generates any network activity.  I had a tcpdump running on the interface and not a single packet the relates to iscsi was captured.  other network traffic (such as this Github interaction) works fine.

Neither dmesg nor Console.app show messages I can relate to this issue.

Any ideas, including how to get better debug information?

**Comment by nsinenian** [comment]
I have not been able to reproduce your problem on Sierra. Do you see any crash logs related to iscsid in the console?

Can you please try disabling discovery to see if the problem disappears? 30 seconds is the default discovery timeout and I am wondering if this is somehow related...

**Comment by BjoKaSH** [comment]
There are no crash logs recorded.  Running `grep -e iscsi -r /var/log` does not return anything relevant (only some "sudo" lines from running dtruss, see below).

I have not configured dynamic discovery, only added a single static target:
```
$ /usr/local/bin/iscsictl list targets
iqn.2013-01.com.example:timemachine2 <inactive, static>
	192.168.178.21 <inactive, port 3260, interface default>

$ /usr/local/bin/iscsictl list discovery-config
SendTargets: disabled
	interval: 300 seconds
	discovery-portals: 0
```

(The actual target uses a valid domain name owned by me, not "example.com". However, that domain name does *not* resolve to 192.168.178.21, the internal IP of the target host.  To my understanding, iSCSI does not use the domain name embedded in the target name.)

I have run `dtruss` against the running iscsi daemon and then run iscsictl for "login" and for "list target-config".  Both iscsictl runs where also monitor using dtruss `sudo dtruss -f -n iscsictl`.  Both dtruss runs for iscsictl are attached (slightly edited by removing repeated lines and early initialisation stuff). The daemon does not show any activity correlated to the iscsictl runs.  Only some periodic housekeeping or so: 
```
$ ps ax | grep -e scsi
  591   ??  Ss     0:00.19 /usr/local/libexec/iscsid
 4111 s000  S+     0:00.00 grep -e scsi
$ sudo dtruss -p 591
Password:
SYSCALL(args) 		 = return
workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
thread_selfid(0x0, 0x0, 0x0)		 = 192389 0
workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
kevent_qos(0x3, 0x7FFF957F61E8, 0x1)		 = 0 0
kevent_qos(0x3, 0x0, 0x0)		 = 1 0
thread_selfid(0x0, 0x0, 0x0)		 = 192395 0
workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
__disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
__disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
madvise(0x102601000, 0x1000, 0x5)		 = 0 0
thread_selfid(0x700000013000, 0x83000, 0x3733)		 = 192505 0
kevent_qos(0x3, 0x0, 0x0)		 = 1 0
workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
thread_selfid(0x0, 0x0, 0x0)		 = 193859 0
workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0
kevent_qos(0x3, 0x7FFF957F61E8, 0x1)		 = 0 0
thread_selfid(0x0, 0x0, 0x0)		 = 193864 0
kevent_qos(0x3, 0x0, 0x0)		 = 1 0
workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
__disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
__disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
madvise(0x103201000, 0x1000, 0x5)		 = 0 0
thread_selfid(0x700000013000, 0x83000, 0x3737)		 = 193992 0
thread_selfid(0x700000096000, 0x83000, 0x392B)		 = 194663 0
```

Interesting are the following snippets from tracing iscsictl. The `iscsictl login` produces:
```
4159/0x2f1b3:  bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
 4159/0x2f1a3:  socket(0x1, 0x1, 0x0)		 = 5 0
 4159/0x2f1a3:  fcntl(0x5, 0x3, 0x545C898C)		 = 2 0
 4159/0x2f1a3:  fcntl(0x5, 0x4, 0x4)		 = 0 0
 4159/0x2f1a3:  connect(0x5, 0x7FFF545C8990, 0x11)		 = 0 0
 4159/0x2f1a3:  select(0x5, 0x0, 0x7FFF545C88F0, 0x0, 0x7FFF545C8970)		 = 0 0
 4159/0x2f1a3:  getsockopt(0x5, 0xFFFF, 0x1007)		 = 0 0
 4159/0x2f1a3:  fcntl(0x5, 0x4, 0x0)		 = 0 0
 4159/0x2f1a3:  setsockopt(0x5, 0xFFFF, 0x1005)		 = 0 0
 4159/0x2f1a3:  setsockopt(0x5, 0xFFFF, 0x1006)		 = 0 0
 4159/0x2f1a3:  sendmsg(0x5, 0x7FFF545C4950, 0x0)		 = 140 0
 4159/0x2f1b3:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4159/0x2f1b3:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4159/0x2f1b3:  madvise(0x10C601000, 0x1000, 0x5)		 = 0 0
 4159/0x2f1ba:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4159/0x2f1ba:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4159/0x2f1a3:  recvmsg(0x5, 0x7FFF545C4950, 0x0)		 = -1 Err#35
 4159/0x2f1a3:  recvmsg(0x5, 0x7FFF545C4950, 0x0)		 = -1 Err#40
 4159/0x2f1a3:  sendmsg(0x5, 0x7FFF545C4950, 0x0)		 = 250 0
   43/0x2f1da:  thread_selfid(0x700000000000, 0x83000, 0xF03)		 = 192986 0
 4159/0x2f1a3:  recvfrom(0x5, 0x7FFF545C89E8, 0x18)		 = -1 Err#35
 4159/0x2f1a3:  workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0

 4159/0x2f1a3:  sendmsg(0x5, 0x7FFF545C4910, 0x0)		 = 282 0
 4159/0x2f1eb:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4159/0x2f1eb:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4159/0x2f1ee:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4159/0x2f1ee:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4159/0x2f1a3:  recvfrom(0x5, 0x7FFF545C89B8, 0x18)		 = -1 Err#35
 4159/0x2f1a3:  close(0x5)		 = 0 0
```

And the `iscsictl list traget-config` produces:
```
 4184/0x2fb06:  bsdthread_ctl(0x100, 0x10FF, 0xFFFFFFFF)		 = 0 0
 4184/0x2fafd:  socket(0x1, 0x1, 0x0)		 = 5 0
 4184/0x2fafd:  fcntl(0x5, 0x3, 0x5933884C)		 = 2 0
 4184/0x2fafd:  fcntl(0x5, 0x4, 0x4)		 = 0 0
 4184/0x2fafd:  connect(0x5, 0x7FFF59338850, 0x11)		 = 0 0
 4184/0x2fafd:  select(0x5, 0x0, 0x7FFF593387B0, 0x0, 0x7FFF59338830)		 = 0 0
 4184/0x2fafd:  getsockopt(0x5, 0xFFFF, 0x1007)		 = 0 0
 4184/0x2fafd:  fcntl(0x5, 0x4, 0x0)		 = 0 0
 4184/0x2fafd:  setsockopt(0x5, 0xFFFF, 0x1005)		 = 0 0
 4184/0x2fafd:  setsockopt(0x5, 0xFFFF, 0x1006)		 = 0 0
 4184/0x2fafd:  sendmsg(0x5, 0x7FFF59334810, 0x0)		 = 140 0
 4184/0x2fb06:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4184/0x2fb06:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4184/0x2fb04:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4184/0x2fb04:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4184/0x2fb04:  madvise(0x107401000, 0x1000, 0x5)		 = 0 0
   44/0x2fb21:  thread_selfid(0x700000000000, 0x83000, 0xF03)		 = 195361 0
 4184/0x2fafd:  recvmsg(0x5, 0x7FFF59334810, 0x0)		 = -1 Err#35
 4184/0x2fafd:  recvmsg(0x5, 0x7FFF59334810, 0x0)		 = -1 Err#40
 4184/0x2fafd:  write(0x3, "iqn.2013-01.com.example:timemachine2 <inactive, static>\n\0", 0x39)		 = 57 0
 4184/0x2fafd:  write(0x3, "\tnode-alias: \n\0", 0xE)		 = 14 0
 4184/0x2fafd:  write(0x3, "\tauto-login: enabled\n\0", 0x15)		 = 21 0
 4184/0x2fafd:  write(0x3, "\tpersistent: yes\n\0", 0x11)		 = 17 0
 4184/0x2fafd:  getaudit_addr(0x7FFF593386C0, 0x30, 0x11)		 = 0 0
 4184/0x2fafd:  __mac_syscall(0x7FFF929F2C06, 0x4, 0x7FFF59337FF8)		 = -1 Err#45
 4184/0x2fafd:  stat64("/Users/bj/Library/Preferences/com.apple.security.plist\0", 0x7FFF593385D0, 0x7FFF59337FF8)		 = -1 Err#2
 4184/0x2fafd:  stat64("/Library/Preferences/com.apple.security-common.plist\0", 0x7FFF593385D0, 0x7FFF59337FF8)		 = -1 Err#2
 4184/0x2fafd:  workq_kernreturn(0x20, 0x0, 0x1)		 = 0 0

### messing around with the Security Framework and MDS, then

 4184/0x2fafd:  write(0x3, "\tConfiguration:\n\t\tMaxConnections (1)\n\t\tErrorRecoveryLevel (0)\n\t\tHeaderDigest (none)\n\t\tDataDigest (none)\0", 0x67)		 = 103 0
 4184/0x2fafd:  write(0x3, "\n\tAuthentication: none\n\t\tCHAP-name \n\t\tCHAP-secret <specified>\n\0", 0x3E)		 = 62 0
 4184/0x2fafd:  sendmsg(0x5, 0x7FFF59334800, 0x0)		 = 250 0
 4184/0x2fb23:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4184/0x2fb23:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4184/0x2fb26:  workq_kernreturn(0x4, 0x0, 0x0)		 = 0 0
 4184/0x2fb26:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
 4184/0x2fafd:  recvmsg(0x5, 0x7FFF59334800, 0x0)		 = -1 Err#35
   47/0x2fb3c:  thread_selfid(0x700000096000, 0x83000, 0xF0B)		 = 195388 0
 3948/0x2fb40:  thread_selfid(0x700000000000, 0x83000, 0x110B)		 = 195392 0
 4184/0x2fafd:  recvmsg(0x5, 0x7FFF59334800, 0x0)		 = -1 Err#35
 4184/0x2fafd:  write(0x3, "\t192.168.178.21 <inactive, port 3260, interface default>\nexample:timemachine2 <inactive, static>\n\0", 0x39)		 = 57 0
 4184/0x2fafd:  close(0x3)		 = 0 0
```

Note the `sendmsg` calls and all failing `recvmsg` calls.  Error 35 is "EAGAIN".

Question: Are there (hidden) options to the get a verbose log of what iscsid and iscsictl are trying to do?  The dtrace output is not particular helpful ...

Attached files:
[dtrace-iscsictl-login.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/683369/dtrace-iscsictl-login.txt)
[dtrace-iscsictl-list-target-config.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/683374/dtrace-iscsictl-list-target-config.txt)

**Comment by BjoKaSH** [comment]
Just a quick note: After double-reboot the login succeeds and the disk appears on the desktop, but now I am in a panic - reboot - panic loop.
More details later, no time right now.

**Comment by nsinenian** [comment]
> Question: Are there (hidden) options to the get a verbose log of what iscsid and iscsictl are trying to do? The dtrace output is not particular helpful ...

No, not for release builds. If you build from sources and install there is some debug logging but that may or may not help.

Did you have these problems with Beta4? Can you reproduce the problem when not using Time Machine on the drive?

I suggest the following: boot into recovery console, disable SIP to break the loop (to prevent the kext from loading). Then, I'd suggest grabbing the kernel crash logs to see why the kernel crashed (the loop you described) and post them here. That may shed some light on what is going on, because this behavior is very strange.

**Comment by BjoKaSH** [comment]
So, back with a bit of time and more details.

> Did you have these problems with Beta4? Can you reproduce the problem when not using Time Machine on the drive?

I never before used the iSCSIInitiator on this machine, so it is a fresh install of Beta5 on a fresh install of the El Capitan OS.  No other non-Apple kext installed and almost no other software so far.

## Steps taken:
As said, I rebooted to see if the iSCSIInitiator would start work again:
  - Booted into recovery mode
  - Switched SIP from "disabled" to "enable --without kext"  (n.b. I would really appreciate a signed kext - running with SIP disabled for long is a no-go for this particular machine.)
 - Rebooted into normal system.

## Result:
- System seemed to work for about 50 minutes.  The external disk was automatically (re)connected  right after startup (or login, unclear) and was shown on the desktop. (Finder setting "show disks on desktop" is on.)
- Unnoticed by me,  iscsid crashed only seconds after the reboot for three times in a row, about every 10 seconds and after one hour another six times in a row, again about every 10 seconds.  Two of the  crash logs are attached. There is a single entry `04/01/17 11:17:28,234 iscsid[74]: kernel extension has not been loaded, iSCSI services unavailable` in the log, but this is early in the boot and might be a race-condition.
- Suddenly the system became unresponsive (Finder and Dock froze, about a minute later mouse pointer froze, then disappeared).  Another minute or two later the system crashed.  Kernel panic log attached.

## Result of panic reboot:
- System came back and allowed login.  Dock and Finder froze in less than one minute, but open programs (Console, SystemPreferences) where still responsive.
- System crashed with another kernel panic within two minutes.
- Between boot and kernel panic five more crash-logs for iscsid had been recorded (again roughly every 10 seconds), in addition to the kernel panic log of the previous crash.

## Further steps:
- Booted into recovery and fully re-enabled SIP to break panic loop (thanks for the tip, although in this case I had already known it 😃 ), then booted into safemode
- No kernel panic log from the second panic.  Probably lost due to boot into recovery mode and then safemode.
- this report.

I may have a bit time tomorrow (Thursday) afternoon (CET) to dig deeper.  Do you think it is worthwhile to compile from source and try again?  Any specific options / settings I should try?  And should I try master or the tagged release?

## Attached files
[Kernel_2017-01-04-121502_hobambp_panic.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/685754/Kernel_2017-01-04-121502_hobambp_panic.txt)
[iscsid_2017-01-04-111748_hobambp_crash.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/685755/iscsid_2017-01-04-111748_hobambp_crash.txt)
[iscsid_2017-01-04-121506_hobambp_crash.txt](https://github.com/iscsi-osx/iSCSIInitiator/files/685756/iscsid_2017-01-04-121506_hobambp_crash.txt)

**Comment by nsinenian** [comment]
If you have time, I would suggest that you download and build from sources (use develop branch), which may produce more useful information and allow for debugging of iscsid while it is running if you find that you can consistently reproduce a problem.

As for the kernel crashes, I'm not sure what effect "enable --without kext" will have. SIP is more than just about the kext, it also restricts writes/access to certain parts of the system. This may or may not include, for example, the location of the socket that is used to communicate with iscsid, the preferences file that is stored on disk, and more. I would stick to doing all testing with SIP fully disabled, and let me know what you are able to consistently reproduce.

**Comment by nsinenian** [comment]
@BjoKaSH Any update on this? Can you please try BETA6?

**Comment by serenissimo1** [comment]
I tried and all working perfectly since the day in which I have installed
the beta6.


--
Alberto Pelizzaro - Via Mazzini 11 30171 Venezia - Mestre


Da: Nareg Sinenian <notifications@github.com> <notifications@github.com>
Rispondi: iscsi-osx/iSCSIInitiator
<reply@reply.github.com>
<reply@reply.github.com>
Data: 10 giugno 2017 at 15:57:25
A: iscsi-osx/iSCSIInitiator <iscsiinitiator@noreply.github.com>
<iscsiinitiator@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Soggetto:  Re: [iscsi-osx/iSCSIInitiator] Unresponsive: No target-login
possible after sleep on El Capitan. No network activity. (#80)

@BjoKaSH <https://github.com/bjokash> Any update on this? Can you please
try BETA6?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iscsi-osx/iSCSIInitiator/issues/80#issuecomment-307566696>,
or mute the thread
