### ISSUE TITLE
Target was not found issue

### ISSUE THREAD

**Issue by simplemal** [iscsi-osx/iSCSIInitiator#84]
# Setup
NAS4Free with iSCSI Target active on ZFS volume.
No authentication required.
Client: MacOS 10.12.3. 

# Problem
I add my target without problems:

`#iscsictl add target iqn.2007-09.jp.ne.peach.istgt:MacContents,10.0.0.10:3260`
`#iscsictl list targets`

response:
`iqn.2007-09.jp.ne.peach.istgt:MacContents <inactive, static>
	10.0.0.10 <inactive, port 3260, interface default>`

but when I try to login with the command
`iscsictl login iqn.2007-09.jp.ne.peach.istgt:MacContents`

the response was:
`iscsictl: Target was not found`

# Workaround
I think there is something wrong in the NAS4free configuration, because I used FreeNAS ten days ago and iscsictl worked well with those same parameters (but it frequently disconnect, btw). Using globalSAN iSCSI Initiator (trial version) I got also an error, but I fix it activating the iSCSI option "Alway send SessionType when connecting". After that, always works fine. It would be useful to have something like that in the new version of iscsictl.

**Comment by nsinenian** [comment]
This initiator always sends out the session type. I'm not sure what it is that globalSAN does - it may be more than simply the session type when you check that box. I would suggest you use WireShark to monitor the traffic.

It is a bad idea to incorporate patches for specific targets. It's generally a bad idea to do this in any software to accommodate something else that isn't standards compliant. If there is actually a bug in the initiator, I'm happy to accommodate.
