### ISSUE TITLE
iscsictl permission denied

### ISSUE THREAD

**Issue by broncobenshea** [iscsi-osx/iSCSIInitiator#87]
I am getting an error message every time I enter a command into the terminal window. 

how can I change permissions? thank you!

$ iscsictl add target iqn.2000-01.com.synology:sciarrino1515.photos,192.168.1.49
iscsictl: Permission denied

**Comment by nsinenian** [comment]
It sounds like you may have an installation issue. Have you disabled system protection (both for installation but also for ongoing use).

Can you also post the output of the three commands:

ls -l /usr/local/libexec

ls -l /usr/local/bin/iscsictl

ioreg | grep iSCSI

**Comment by broncobenshea** [comment]
csrutil is disabled and I am still getting a permission denied error

I'm not sure what you mean when you say disabled system protection for ongoing use

Christine$ ls -l /usr/local/libexec
total 880
-rwxr-xr-x  1 root  wheel  304032 Aug 31  2016 MCTTriggerDriver
-rwxr--r--  1 root  wheel  142168 Mar 16 10:50 iscsid
iMac:~ Christine$ ls -l /usr/local/bin/iscsictl
-rwxr-xr-x  1 root  wheel  105620 Mar 16 10:50 /usr/local/bin/iscsictl
iMac:~ Christine$ ioreg | grep iSCSI
      +-o com_github_iscsi_osx_iSCSIInitiator  <class com_github_iscsi_osx_iSCSIInitiator, id 0x100000460, registered, matched, active, busy 0 (24 ms), retain 6>
      | +-o com_github_iscsi_osx_iSCSIVirtualHBA  <class com_github_iscsi_osx_iSCSIVirtualHBA, id 0x100000466, registered, matched, active, busy 0 (24 ms), retain 7>
      |               +-o SYNOLOGY iSCSI Storage Media  <class IOMedia, id 0x1000005b6, registered, matched, active, busy 0 (9 ms), retain 10>

**Comment by broncobenshea** [comment]
Do you think that installing a new beta would solve this problem?

**Comment by broncobenshea** [comment]
![screen shot 2017-05-24 at 10 31 35 am](https://cloud.githubusercontent.com/assets/6504282/26416861/33d9af8a-406c-11e7-8de5-89dca3de943e.png)

**Comment by broncobenshea** [comment]
![screen shot 2017-05-24 at 10 32 25 am](https://cloud.githubusercontent.com/assets/6504282/26416897/4cf45d12-406c-11e7-9161-21fc9b03210b.png)

**Comment by broncobenshea** [comment]
I noticed in the wiki that you say " Ensure that no iSCSI targets are connected when updating or removing the initiator software, or you may experience an error during installation." but I get 'permission denied' messages when I try to modify anything

**Comment by broncobenshea** [comment]
SOLUTION
i deleted the permissions file using 'sudo rm /Library/Preferences/com.github.iscsi-osx.iSCSIInitiator.plist' that you recommended to another user. > uninstalled software > shutdown > reinstalled software > shutdown 

no longer receiving the permission denied error
