### ISSUE TITLE
build not documented

### ISSUE THREAD

**Issue by abonillasuse** [iscsi-osx/iSCSIInitiator#9]
The README expects that the Kernel and Tools have already built, but there are no instructions on how to build them. Can you provide a quick overview?

**Comment by Eveink** [comment]
https://developer.apple.com/library/ios/technotes/tn2339/_index.html

xcodebuild -scheme iscsictl build

**Comment by abonillasuse** [comment]
± |master ✓| → xcodebuild -scheme iscsictl build
xcodebuild: error: The project named "iSCSIInitiator" does not contain a scheme named "iscsictl". The "-list" option can be used to find the names of the schemes in the project.

Information about project "iSCSIInitiator":
    Targets:
        iSCSIInitiator
        iSCSIDaemon
        iscsictl
        iSCSITest

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    This project contains no schemes.
