### ISSUE TITLE
Cannot login to any targets; MacOS Sierra 10.12.4

### ISSUE THREAD

**Issue by arealwookie** [iscsi-osx/iSCSIInitiator#90]
Newbie here. Followed instructions on wiki and cannot login, ie. "target not found" Trying to access iscsi share on FreeNas Corral. Need to access my Final Cut Pro X Library on NAS. What am I doing wrong? Here is a cut and paste from the terminal:

unobtanium:~ bruce$ iscsictl list luns
No active targets with LUNs exist
unobtanium:~ bruce$ iscsictl login iqn.2005-10.org.freenas.ctl:fcpx
iscsictl: Target was not found
unobtanium:~ bruce$ iscsictl list initiator-config
iqn.2015-01.com.localhost:initiator
	node-alias localhost
	Authentication: none
		CHAP-name localhost
		CHAP-secret <unspecified>
unobtanium:~ bruce$ iscsictl list targets
iqn.2005-10.org.freenas.ctl:fcpx <inactive, static>
	192.168.0.11 <inactive, port 3260, interface default>
iqn.2005-10.org.freenas.ctl:test <inactive, static>
	192.168.0.11 <inactive, port 3260, interface default>
unobtanium:~ bruce$ iscsictl add discovery-portal 192.168.0.11
The specified discovery portal already exists
unobtanium:~ bruce$ iscsictl modify discovery-config -SendTargets enable
Discovery settings have been updated
unobtanium:~ bruce$ iscsictl list discovery-config
SendTargets: enabled
	interval: 60 seconds
	discovery-portals: 1
		192.168.0.11    <port 3260, interface default>
unobtanium:~ bruce$ iscsictl login iqn.2005-10.org.freenas.ctl:fcpx,192.168.0.11
iscsictl: Target was not found
unobtanium:~ bruce$ 

Globalsan trial works but is running out...

**Comment by nsinenian** [comment]
It may be a case of target forwarding -- which the current version of the initiator does not support (not yet implemented)

To confirm: can you please use Wireshark to capture traffic during attempted login (i.e., start Wireshark capture, execute 'iscsictl login ...'  and once you get the error message stop capture and post the file here).

**Comment by arealwookie** [comment]
I am not familiar with Wireshark, but I will give it a try. Attached is the ouput. I hope this is what you are asking for. The FreeNas server I am trying to make an iscsi logon connection with is @ 192.168.0.11 from 192.168.0.10. Thanks. 
[ wireshark output.pcapng.zip](https://github.com/iscsi-osx/iSCSIInitiator/files/999537/wireshark.output.pcapng.zip)

**Comment by nsinenian** [comment]
@arealwookie Something is wrong with the capture - no iSCSI traffic has been recorded. Are you starting the capture PRIOR to issuing the login command?

**Comment by NordicFlyer** [comment]
Updated to FreeNas 11, iSCSIInitiator beta 6, and Mac OS Sierra 10.12.5 and followed the wiki instructions. Everything works as expected and I am finally able to logon to my iscsi block shares. Thanks...please consider this issue closed.
