### ISSUE TITLE
PowerNap

### ISSUE THREAD

**Issue by drviver** [iscsi-osx/iSCSIInitiator#91]
Is it possible to prevent the scsi from sleeping, if there is currently an operation, like a time machine backup. Since it is developed as an kernel extension this should be possible I think, but sadly I am not into kernel programming all that much.
I would really appreciate it, and also, great work, I appreciate it
:) keep it up

**Comment by nsinenian** [comment]
It is in fact not possible. Apple controls which services run under power nap -- developers have no control over this as far as I know.

**Comment by drviver** [comment]
but with system integrity disabled, one can modify the system, means also power nap, but yeah I know, that would be very hard to program, since it requires to reverse engineer an app like time machine, to understand how exactly it works

**Comment by nsinenian** [comment]
SIP is disabled only temporarily until development is complete. The power
nap APIs are not available to end users regardless which is an entirely
different issue Fromm SIP.
